import { Categoria, ModeloFicha, merge } from './_shared'

// ─────────────────────────────────────────────────────────────────────────────
// DODGE JOURNEY 2026
// ─────────────────────────────────────────────────────────────────────────────

const JOURNEY_SXT: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                   valor: '1.5 L Turbo DCVVT 4I GDI' },
      { label: 'Potencia',                valor: '156 HP' },
      { label: 'Torque',                  valor: '184 lb-pie' },
      { label: 'Transmisión',             valor: 'Automática 6 velocidades' },
      { label: 'Suspensión delantera',    valor: 'McPherson independiente' },
      { label: 'Suspensión trasera',      valor: 'Multi-link independiente' },
      { label: 'Frenos delanteros',       valor: 'Discos ventilados' },
      { label: 'Frenos traseros',         valor: 'Discos' },
      { label: 'Dirección',               valor: 'EPS (Asistencia Eléctrica)' },
      { label: 'Rines',                   valor: 'Aluminio bitono 18" cara pulida' },
      { label: 'Neumáticos',              valor: '235/55' },
      { label: 'Consumo carretera',       valor: '18.90 km/l' },
      { label: 'Consumo ciudad',          valor: '12.66 km/l' },
      { label: 'Consumo combinado',       valor: '14.87 km/l' },
      { label: 'Longitud',                valor: '4,695 mm' },
      { label: 'Ancho',                   valor: '1,885 mm' },
      { label: 'Altura',                  valor: '1,700 mm' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Faros delanteros',           valor: 'Halógenos' },
      { label: 'Faros de niebla',            valor: 'LED' },
      { label: 'DRL',                        valor: 'LED' },
      { label: 'Luces traseras',             valor: 'LED' },
      { label: 'Alerón trasero con luz LED', valor: 'Sí' },
      { label: 'Espejos laterales',          valor: 'Eléctricos abatibles, calefactables, con luz direccional' },
      { label: 'Espejos con tilt down',      valor: 'No incluido' },
      { label: 'Quemacocos',                 valor: 'Estándar (protección contra atascos)' },
      { label: 'Techo panorámico',           valor: 'No incluido' },
      { label: 'Cajuela eléctrica',          valor: 'No incluida' },
      { label: 'Estribos laterales',         valor: 'No incluidos' },
      { label: 'Rieles en techo',            valor: 'Funcionales integrados' },
      { label: 'Sensor de lluvia/luz',       valor: 'Sí' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',                       valor: 'Tela con insertos en piel sintética' },
      { label: 'Asiento conductor',               valor: 'Eléctrico 8 vías' },
      { label: 'Asiento pasajero',                valor: 'Manual' },
      { label: 'Memoria asiento conductor',       valor: 'No incluida' },
      { label: 'Asientos calefactables/ventilados', valor: 'No incluidos' },
      { label: 'Pantalla principal',              valor: '10" LCD' },
      { label: 'Panel de instrumentos',           valor: '12.3" LCD' },
      { label: 'A/C',                             valor: 'Automático doble zona' },
      { label: 'Espejo retrovisor interior',      valor: 'Manual día/noche' },
      { label: 'Iluminación ambiental',           valor: 'No incluida' },
      { label: 'Cargador inalámbrico',            valor: 'No incluido' },
      { label: 'Purificador de aire',             valor: 'No incluido' },
      { label: 'Segunda fila',                    valor: 'Abatible 60/40 y respaldos reclinables' },
      { label: 'Puertos USB delanteros',          valor: '2' },
      { label: 'Filtro de aire PM 2.5',           valor: 'Sí' },
      { label: 'Volante',                         valor: 'Multifuncional en piel, ajuste altura y profundidad' },
    ],
  },
  {
    id: 'tecnologia', nombre: 'Tecnología y Entretenimiento', specs: [
      { label: 'Apple CarPlay',              valor: 'No incluido' },
      { label: 'Android Auto',               valor: 'No incluido' },
      { label: 'MirrorLink®',                valor: 'No incluido' },
      { label: 'Keyless Entry & GO®',        valor: 'No incluido' },
      { label: 'Cámara de reversa',          valor: 'Sí' },
      { label: 'Visión 360°',                valor: 'No incluida' },
      { label: 'Audio',                      valor: '6 bocinas' },
      { label: 'Cargador tel. inalámbrico',  valor: 'No incluido' },
      { label: 'Cierre express',             valor: 'No incluido' },
      { label: 'Modo Sport',                 valor: 'No incluido' },
      { label: 'Sistema Start & Stop',       valor: 'Sí' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'ABS',                                    valor: 'Sí' },
      { label: 'ESP (Estabilidad Electrónica)',           valor: 'Sí' },
      { label: 'EBD (Distribución de frenado)',          valor: 'Sí' },
      { label: 'Freno de estacionamiento (EPB + AutoHold)', valor: 'Sí' },
      { label: 'Bolsas de aire',                         valor: 'Frontales + cortina + laterales delanteras' },
      { label: 'Advertencia colisión frontal (FCW)',     valor: 'No incluida' },
      { label: 'Advertencia salida de carril (LDW)',     valor: 'No incluida' },
      { label: 'Descenso de pendientes (HDC)',           valor: 'No incluido' },
      { label: 'Luces inteligentes Smartbeam',           valor: 'No incluidas' },
      { label: 'Arranque en pendiente (HSA)',            valor: 'Sí' },
      { label: 'Frenado hidráulico (HBA)',               valor: 'Sí' },
      { label: 'Sensores de estacionamiento',            valor: 'Delanteros y traseros' },
      { label: 'Cinturones 2ª fila con pretensores',    valor: 'No incluidos' },
      { label: 'ISOFIX',                                 valor: 'Sí' },
      { label: 'TPMS (presión de llantas)',              valor: 'Sí' },
      { label: 'Alarma antirrobo',                       valor: 'Sí' },
    ],
  },
]

const JOURNEY_SPORT: Categoria[] = merge(JOURNEY_SXT, {
  desempeno: {
    'Rines':              'Aluminio bitono 19" cara pulida',
    'Neumáticos':         '235/50',
  },
  exterior: {
    'Faros delanteros':  'LED',
    'Espejos con tilt down': 'Sí',
  },
  interior: {
    'Tapicería':                         'Piel sintética Leatherette negra',
    'Asiento conductor':                 'Eléctrico 10 vías con 3 memorias y entrada de cortesía',
    'Asiento pasajero':                  'Eléctrico 4 vías',
    'Memoria asiento conductor':         'Sí (3 memorias)',
    'Asientos calefactables/ventilados': 'Sí (3 niveles ajustables)',
    'Espejo retrovisor interior':        'Automático día/noche con USB',
    'Iluminación ambiental':             'Sí',
    'Cargador inalámbrico':              'Sí',
  },
  tecnologia: {
    'Apple CarPlay':             'Sí',
    'Android Auto':              'Sí',
    'Keyless Entry & GO®':       'Sí',
    'Cámara de reversa':         '— (incluido en visión 360°)',
    'Visión 360°':               'Sí',
    'Cargador tel. inalámbrico': 'Sí',
    'Cierre express':            'Sí (cristales y quemacocos)',
  },
  seguridad: {
    'Advertencia colisión frontal (FCW)':  'Sí',
    'Advertencia salida de carril (LDW)':  'Sí',
    'Descenso de pendientes (HDC)':        'Sí',
    'Luces inteligentes Smartbeam':        'Sí',
    'Cinturones 2ª fila con pretensores':  'Sí',
  },
})

const JOURNEY_GT_PLUS: Categoria[] = merge(JOURNEY_SPORT, {
  desempeno: {
    'Consumo carretera': '18.19 km/l',
    'Consumo ciudad':    '12.45 km/l',
    'Consumo combinado': '14.51 km/l',
  },
  exterior: {
    'Quemacocos':       'Techo panorámico',
    'Cajuela eléctrica':'Eléctrica con apertura intermedia y anti atrapadura',
    'Estribos laterales':'Sí (con logotipo DODGE)',
  },
  interior: {
    'Purificador de aire': 'Sí (ionizador de iones negativos)',
  },
  tecnologia: {
    'MirrorLink®':  'Sí',
    'Modo Sport':   'Sí',
    'Audio':        '8 bocinas',
  },
})

// ─────────────────────────────────────────────────────────────────────────────
// DODGE ATTITUDE 2026
// ─────────────────────────────────────────────────────────────────────────────

const ATTITUDE_SXT: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                 valor: '1.5L Turbo GDI' },
      { label: 'Potencia',              valor: '168 HP' },
      { label: 'Torque',                valor: '184 lb-ft' },
      { label: 'Transmisión',           valor: 'Automática 7 vel. doble embrague (DCT)' },
      { label: 'Suspensión delantera',  valor: 'McPherson independiente' },
      { label: 'Suspensión trasera',    valor: 'Multi-link Beam' },
      { label: 'Frenos delanteros',     valor: 'Discos ventilados' },
      { label: 'Frenos traseros',       valor: 'Discos' },
      { label: 'Dirección',             valor: 'EPS (Asistencia Eléctrica)' },
      { label: 'Rines',                 valor: 'Aluminio bitono cara pulida 17"' },
      { label: 'Neumáticos',            valor: '225/50 R17' },
      { label: 'Consumo carretera',     valor: '22.55 km/l' },
      { label: 'Consumo ciudad',        valor: '15.43 km/l' },
      { label: 'Consumo combinado',     valor: '17.98 km/l' },
      { label: 'Longitud',              valor: '4,700 mm' },
      { label: 'Ancho',                 valor: '1,850 mm' },
      { label: 'Altura',                valor: '1,432 mm' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Faros delanteros',          valor: 'LED (ajuste de altura / función "Sígueme a casa")' },
      { label: 'DRL',                        valor: 'LED' },
      { label: 'Luces de niebla traseras',   valor: 'Sí' },
      { label: 'Faros automáticos',          valor: 'Sí' },
      { label: 'Alerón trasero',             valor: 'No incluido' },
      { label: 'Espejos laterales',          valor: 'Con ajuste eléctrico' },
      { label: 'Espejos abatibles',          valor: 'No incluidos (solo ajuste eléctrico)' },
      { label: 'Espejos calefactables',      valor: 'No incluidos' },
      { label: 'Espejos con señal de giro',  valor: 'No incluidos' },
      { label: 'Doble salida de escape',     valor: 'Cromada' },
      { label: 'Sensor de lluvia',           valor: 'Sí' },
      { label: 'Colores disponibles',        valor: 'Blanco brillante, Granito' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',                      valor: 'Tela' },
      { label: 'A/C',                             valor: 'Manual' },
      { label: 'Asiento conductor',              valor: 'Ajuste manual 6 vías' },
      { label: 'Asiento pasajero',               valor: 'Manual' },
      { label: 'Asientos ventilados',            valor: 'No incluidos' },
      { label: 'Keyless Entry & Go®',             valor: 'No incluido' },
      { label: 'Espejo retrovisor',              valor: 'Día/noche manual' },
      { label: 'Iluminación ambiental',          valor: 'No incluida' },
      { label: 'Paletas de cambio al volante',   valor: 'No incluidas' },
      { label: 'Quemacocos eléctrico',           valor: 'No incluido' },
      { label: 'Apoyo lumbar conductor',         valor: 'No incluido' },
      { label: 'Apoyabrazos 2ª fila',            valor: 'No incluido' },
      { label: 'Salida de aire trasera',         valor: 'No incluida' },
      { label: 'Ventanas un solo toque',         valor: 'No incluidas' },
      { label: 'Volante',                        valor: 'Sin forro en piel' },
      { label: 'Tomacorriente 12V',              valor: 'Sí (1ª fila)' },
      { label: 'Filtro de aire',                 valor: 'Sí' },
    ],
  },
  {
    id: 'tecnologia', nombre: 'Tecnología y Entretenimiento', specs: [
      { label: 'Panel de instrumentos',          valor: 'LCD 7" configurable' },
      { label: 'Pantalla infotainment',          valor: 'No incluida' },
      { label: 'Audio',                          valor: 'DTS 6 bocinas' },
      { label: 'Android Auto',                   valor: 'Sí' },
      { label: 'Apple CarPlay / MirrorLink',     valor: 'No incluido' },
      { label: 'Cargador inalámbrico',           valor: 'No incluido' },
      { label: 'Puertos USB 1ª fila',            valor: '2' },
      { label: 'Puerto USB 2ª fila',             valor: 'No incluido' },
      { label: 'Sonido de escape',               valor: 'No incluido' },
      { label: 'Sistema de manos libres',        valor: 'Sí' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'ABS',                                   valor: 'Sí' },
      { label: 'ESP (Estabilidad Electrónica)',          valor: 'Sí' },
      { label: 'EBD (Distribución de frenado)',         valor: 'Sí' },
      { label: 'EPB + AutoHold',                        valor: 'Sí' },
      { label: 'AEB (Frenado Autónomo de Emergencia)',  valor: 'No incluido' },
      { label: 'HBA (Frenado Hidráulico)',              valor: 'Sí' },
      { label: 'HSA (Arranque en pendiente)',           valor: 'Sí' },
      { label: 'Control de crucero',                    valor: 'Convencional' },
      { label: 'ACC (Crucero Adaptativo)',               valor: 'No incluido' },
      { label: 'FCW (Alerta colisión frontal)',         valor: 'No incluida' },
      { label: 'LDW (Alerta salida de carril)',         valor: 'No incluida' },
      { label: 'LKA (Mantenimiento de carril)',         valor: 'No incluida' },
      { label: 'ICA (Crucero Integrado)',               valor: 'No incluido' },
      { label: 'TJA (Asistente de atasco)',             valor: 'No incluido' },
      { label: 'HMA (Luces altas inteligentes)',        valor: 'No incluido' },
      { label: 'BSD (Detector de punto ciego)',         valor: 'No incluido' },
      { label: 'Cámara de reversa',                    valor: 'Sí' },
      { label: 'Sensores de estacionamiento',          valor: 'Solo traseros' },
      { label: 'Bolsas de aire',                       valor: 'Frontales + cortina + laterales delanteras' },
      { label: 'ISOFIX',                               valor: 'Sí' },
      { label: 'TPMS (presión de llantas)',            valor: 'Sí' },
      { label: 'Alarma antirrobo',                     valor: 'Sí' },
    ],
  },
]

const ATTITUDE_SPORT: Categoria[] = merge(ATTITUDE_SXT, {
  desempeno: {
    'Rines':              'Aluminio bitono cara pulida 18"',
    'Neumáticos':         '225/45 R18',
    'Consumo carretera':  '21.52 km/l',
    'Consumo ciudad':     '15.03 km/l',
    'Consumo combinado':  '17.39 km/l',
  },
  exterior: {
    'Espejos laterales':      'Con ajuste eléctrico + abatibles + calefactables + señal de giro',
    'Espejos abatibles':      'Sí',
    'Espejos calefactables':  'Sí',
    'Espejos con señal de giro': 'Sí',
    'Colores disponibles':    'Blanco brillante, Granito, Plata estelar, Negro brillante',
  },
  interior: {
    'Tapicería':                   'Piel sintética',
    'A/C':                          'Automático doble zona',
    'Asiento conductor':           'Eléctrico 6 vías',
    'Asiento pasajero':            'Manual',
    'Asientos ventilados':         'Sí',
    'Keyless Entry & Go®':          'Sí',
    'Espejo retrovisor':           'Día/noche manual + interfaz USB',
    'Iluminación ambiental':       'Inteligente multicolor',
    'Paletas de cambio al volante':'Sí',
    'Quemacocos eléctrico':        'Sí (antipellizco)',
    'Apoyabrazos 2ª fila':         'Sí',
    'Salida de aire trasera':      'Sí',
    'Ventanas un solo toque':      'Sí (antipellizco)',
    'Volante':                     'Forrado en piel',
  },
  tecnologia: {
    'Panel de instrumentos':      'LCD 10.25" configurable',
    'Pantalla infotainment':      '10.25" LCD a color',
    'Audio':                      'DTS 8 bocinas',
    'Apple CarPlay / MirrorLink': 'Sí (alámbrico)',
    'Puerto USB 2ª fila':         '1',
    'Sonido de escape':           'Sí',
  },
  seguridad: {
    'AEB (Frenado Autónomo de Emergencia)': 'Sí',
    'Control de crucero':                   'ACC (Adaptativo)',
    'ACC (Crucero Adaptativo)':             'Sí',
    'FCW (Alerta colisión frontal)':        'Sí',
    'LDW (Alerta salida de carril)':        'Sí',
    'LKA (Mantenimiento de carril)':        'Sí',
    'ICA (Crucero Integrado)':              'Sí',
    'TJA (Asistente de atasco)':            'Sí',
    'HMA (Luces altas inteligentes)':       'Sí',
    'Sensores de estacionamiento':          'Delanteros y traseros',
  },
})

const ATTITUDE_GT: Categoria[] = merge(ATTITUDE_SPORT, {
  desempeno: {
    'Rines':             'Aluminio negro satinado 18" (Performance)',
    'Neumáticos':        '225/45Z R18 alta velocidad',
    'Consumo carretera': '20.92 km/l',
    'Consumo ciudad':    '14.56 km/l',
    'Consumo combinado': '16.87 km/l',
  },
  exterior: {
    'Alerón trasero': 'Sí',
  },
  interior: {
    'Asiento pasajero':   'Eléctrico 4 vías',
    'Espejo retrovisor':  'Día/noche automático + interfaz USB',
    'Apoyo lumbar conductor': 'Sí (4 direcciones)',
  },
  tecnologia: {
    'Cargador inalámbrico': 'Sí',
  },
  seguridad: {
    'BSD (Detector de punto ciego)': 'Sí',
  },
})

// ─────────────────────────────────────────────────────────────────────────────
// DODGE DURANGO HELLCAT 2026  —  Road Predator Edition + Red Fury
// ─────────────────────────────────────────────────────────────────────────────

const DURANGO_ROAD_PREDATOR: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                      valor: '6.2L supercargado HEMI V8 SRT' },
      { label: 'Potencia',                   valor: '710 HP' },
      { label: 'Torque',                     valor: '645 lb-ft' },
      { label: 'Transmisión',                valor: 'Automática 8 velocidades' },
      { label: 'Tracción',                   valor: 'Quadra-Trac On Demand (AWD)' },
      { label: 'Sistema Selec-Trac',         valor: 'Sí' },
      { label: 'Diferencial trasero',        valor: 'Deslizamiento limitado' },
      { label: 'Dirección',                  valor: 'Eléctrica, ajuste alt. y telescópico, modo seleccionable' },
      { label: 'Suspensión',                 valor: 'De competición' },
      { label: 'Modos de manejo',            valor: 'SPORT + SRT Performance Pages + Launch Control' },
      { label: 'Paletas de cambio',          valor: 'Al volante' },
      { label: 'Aceleración 0-100 km/h',    valor: '3.5 s' },
      { label: 'Arranque',                   valor: 'Botón de arranque + remoto' },
      { label: 'Alternador',                 valor: '220 Amp' },
      { label: 'Batería',                    valor: '700 Amp, libre de mantenimiento' },
      { label: 'Alimentación 12V',           valor: 'Delantera y trasera' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Pasajeros',                  valor: '6 (3 filas)' },
      { label: 'Tapicería',                  valor: 'Piel laguna Demonic Red (alto desempeño)' },
      { label: 'A/C',                        valor: 'Automático 3 zonas' },
      { label: 'Asiento conductor',          valor: '8 vías + 4 vías lumbar, calefactable y ventilado' },
      { label: 'Asiento pasajero',           valor: '8 vías, calefactable y ventilado' },
      { label: '2ª fila',                    valor: 'Tipo capitán, calefactable' },
      { label: 'Consola trasera',            valor: 'Mini consola 2ª y 3ª fila' },
      { label: 'Volante',                    valor: 'SRT forrado en piel calefactable' },
      { label: 'Pantalla',                   valor: '10.1" táctil' },
      { label: 'Navegación',                 valor: 'GPS integrada' },
      { label: 'Audio',                      valor: '19 altavoces Harman Kardon + subwoofer, 825 W' },
      { label: 'Apple CarPlay / Android Auto', valor: 'Sí (inalámbrico)' },
      { label: 'Carga inalámbrica',          valor: 'Sí' },
      { label: 'USB / AUX',                  valor: '2 USB + AUX' },
      { label: 'Retrovisor interior',        valor: 'Electrocrómico' },
      { label: 'Iluminación interior',       valor: 'LED' },
      { label: 'Parabrisas',                 valor: 'Acústico' },
      { label: 'Supresión de ruido activa',  valor: 'Sí' },
      { label: 'Control garage universal',   valor: 'Sí' },
      { label: 'Cinturones',                 valor: 'Color Hammerhead Grey' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Rines',                      valor: '20" × 10" Forged Y-Spoke Lights Out' },
      { label: 'Neumáticos',                 valor: '295/45ZR20 BSW All Season' },
      { label: 'Frenos delanteros',          valor: 'Brembo® con calipers rojos' },
      { label: 'Cofre',                      valor: 'Pintado negro, diseño High Performance' },
      { label: 'Escape',                     valor: 'Doble punta color negro' },
      { label: 'Faros delanteros',           valor: 'LED automáticos' },
      { label: 'DRL',                        valor: 'LED' },
      { label: 'Luces traseras',             valor: 'LED' },
      { label: 'Espejos laterales',          valor: 'Calefactables, plegables, con indicadores y memoria, negro brillante' },
      { label: 'Espejo conductor',           valor: 'Electrocrómico' },
      { label: 'Acceso pasivo',              valor: 'Puertas delanteras' },
      { label: 'Portón trasero',             valor: 'Eléctrico' },
      { label: 'Quemacocos',                 valor: 'Eléctrico' },
      { label: 'Parrilla',                   valor: 'Color negro' },
      { label: 'Rieles en toldo',            valor: 'Negro' },
      { label: 'Color',                      valor: 'Destroyer Grey' },
      { label: 'Largo',                      valor: '5,101 mm' },
      { label: 'Ancho',                      valor: '1,924 mm' },
      { label: 'Alto',                       valor: '1,790 mm' },
      { label: 'Llanta de refacción',        valor: 'Incluida' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS HD',              valor: 'Disco' },
      { label: 'Frenos Brembo®',             valor: 'Delanteros' },
      { label: 'Frenos asistencia lluvia',   valor: 'Sí + Ready Alert' },
      { label: 'Control estabilidad (ESC)',  valor: 'Sí' },
      { label: 'Control tracción (TC)',       valor: 'Sí' },
      { label: 'HSA (arranque en pendiente)', valor: 'Sí' },
      { label: 'Asistencia estacionamiento', valor: 'Frontal y trasero con STOP' },
      { label: 'Punto ciego y ruta transversal', valor: 'Sí' },
      { label: 'Control balance de remolque',valor: 'Sí' },
      { label: 'Cámara trasera',             valor: 'Sí' },
      { label: 'Bolsas de aire',             valor: 'Frontales + laterales + cortina 3 filas + rodilla conductor + complementarias' },
      { label: 'LATCH',                      valor: 'Sí' },
      { label: 'Monitor presión neumáticos', valor: 'Sí' },
      { label: 'Alarma',                     valor: 'Sí + antirrobo centralizado' },
      { label: 'Seguros de puertas',         valor: 'Eléctricos' },
    ],
  },
]

const DURANGO_RED_FURY: Categoria[] = merge(DURANGO_ROAD_PREDATOR, {
  interior: {
    'Pasajeros':       '5 (2 filas)',
    'Tapicería':       'Piel negro (alto desempeño)',
    '2ª fila':         'Calefactable',
    'Consola trasera': 'Mini consola 2ª fila',
    'Cinturones':      'Color rojo',
  },
  exterior: {
    'Color':               'Octane Red',
    'Llanta de refacción': 'No incluida',
  },
  seguridad: {
    'Bolsas de aire': 'Frontales + laterales + cortina + rodilla conductor + complementarias',
  },
})

export const MODELOS_DODGE: ModeloFicha[] = [
  {
    id: 'attitude-2026',
    marca: 'Dodge',
    modelo: 'Attitude',
    año: 2026,
    versiones: [
      { id: 'sxt',   nombre: 'SXT',   categorias: ATTITUDE_SXT },
      { id: 'sport', nombre: 'Sport', categorias: ATTITUDE_SPORT },
      { id: 'gt',    nombre: 'GT',    categorias: ATTITUDE_GT },
    ],
  },
  {
    id: 'journey-2026',
    marca: 'Dodge',
    modelo: 'Journey',
    año: 2026,
    versiones: [
      { id: 'sxt',     nombre: 'SXT',     categorias: JOURNEY_SXT },
      { id: 'sport',   nombre: 'Sport',   categorias: JOURNEY_SPORT },
      { id: 'gt-plus', nombre: 'GT Plus', categorias: JOURNEY_GT_PLUS },
    ],
  },
  {
    id: 'durango-hellcat-2026',
    marca: 'Dodge',
    modelo: 'Durango Hellcat',
    año: 2026,
    versiones: [
      { id: 'road-predator', nombre: 'Road Predator Edition', categorias: DURANGO_ROAD_PREDATOR },
      { id: 'red-fury',      nombre: 'Red Fury',              categorias: DURANGO_RED_FURY      },
    ],
  },
]
