import { Categoria, ModeloFicha, merge } from './_shared'

// ─────────────────────────────────────────────────────────────────────────────
// JEEP GRAND CHEROKEE 2026
// ─────────────────────────────────────────────────────────────────────────────

const GC_BASE: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                        valor: 'Hurricane Turbo W/ESS' },
      { label: 'Potencia',                     valor: '324 hp' },
      { label: 'Torque',                       valor: '332 lb-pie' },
      { label: 'Transmisión',                  valor: 'Automática 8 vel. 8HP80' },
      { label: 'Tracción',                     valor: '4X2 (FWD)' },
      { label: 'Sistema Selec-Terrain®',       valor: 'No incluido' },
      { label: 'Suspensión delantera',         valor: 'Independiente' },
      { label: 'Suspensión trasera',           valor: 'Independiente multilink' },
      { label: 'Suspensión neumática',         valor: 'No incluida' },
      { label: 'Diferencial frontal',          valor: 'No aplica (4X2)' },
      { label: 'Diferencial trasero (LSD)',    valor: 'No incluido' },
      { label: 'Receptor de remolque',         valor: 'No incluido' },
      { label: 'Dirección',                    valor: 'Eléctrica' },
      { label: 'Diámetro de giro',             valor: '11.3 m' },
      { label: 'Peso bruto vehicular',         valor: '2,744 kg' },
      { label: 'Capacidad de carga',           valor: '476 kg' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Pasajeros',                     valor: '5' },
      { label: 'Filas de asientos',             valor: '2' },
      { label: 'Tapicería',                     valor: 'Leatherette y gamuza' },
      { label: 'Techo interior',                valor: 'Negro' },
      { label: 'Asientos delanteros calef.',    valor: 'Sí' },
      { label: 'Asientos delanteros ventilados',valor: 'No incluidos' },
      { label: 'Asientos delanteros con masaje',valor: 'No incluidos' },
      { label: 'Ajuste asiento conductor',      valor: 'Eléctrico 8 vías' },
      { label: 'Memoria asiento conductor',     valor: 'No incluida' },
      { label: 'Ajuste asiento pasajero',       valor: 'Manual 4 vías' },
      { label: 'Memoria asiento pasajero',      valor: 'No incluida' },
      { label: 'Segunda fila',                  valor: '60/40 plegable' },
      { label: 'Segunda fila calefactable',     valor: 'No incluida' },
      { label: 'Segunda fila ventilada',        valor: 'No incluida' },
      { label: 'Segunda fila cortinillas',      valor: 'No incluidas' },
      { label: 'Tercera fila',                  valor: 'No incluida' },
      { label: 'Pantalla principal',            valor: 'Uconnect® 5 — 12.3" táctil' },
      { label: 'Clúster',                       valor: '10.25" TFT a color' },
      { label: 'Head-Up Display',               valor: 'No incluido' },
      { label: 'Pantalla interactiva pasajero', valor: 'No incluida' },
      { label: 'Visualiz. de mapas en clúster', valor: 'No incluida' },
      { label: 'Audio',                         valor: '6 altavoces premium' },
      { label: 'Amplificador',                  valor: 'No especificado' },
      { label: 'Supresión activa de ruido',     valor: 'Sí' },
      { label: 'Apple CarPlay / Android Auto',  valor: 'Sí' },
      { label: 'Iluminación ambiental',         valor: 'No incluida' },
      { label: 'Iluminación cortesía puertas',  valor: 'No incluida' },
      { label: 'Puerto USB 2ª fila',            valor: 'Sí' },
      { label: 'Puerto USB 3ª fila',            valor: 'No aplica' },
      { label: 'Espejo retrovisor interior',    valor: 'Estándar' },
      { label: 'Columna dirección con memoria', valor: 'No incluida' },
      { label: 'Control apertura de garage',    valor: 'No incluido' },
      { label: 'Aire acondicionado',            valor: 'Automático doble zona' },
      { label: 'Volante',                       valor: 'Tecnopiel' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Neumáticos',            valor: '265/50R20 Performance A/S' },
      { label: 'Rines',                 valor: 'Aluminio 20×8.5 negro brillante' },
      { label: 'Quemacocos',            valor: 'Eléctrico' },
      { label: 'Techo panorámico',      valor: 'No incluido' },
      { label: 'Exterior bitono',       valor: 'No' },
      { label: 'Luces delanteras',      valor: 'LED automáticas' },
      { label: 'Faros de niebla',       valor: 'No incluidos' },
      { label: 'Luces traseras',        valor: 'LED' },
      { label: 'Espejos plegado',       valor: 'Manual' },
      { label: 'Espejos señalización',  valor: 'No incluida' },
      { label: 'Maletero',              valor: 'Apertura eléctrica' },
      { label: 'Rieles en techo',       valor: 'Negro brillante' },
      { label: 'Longitud',              valor: '4,915 mm' },
      { label: 'Ancho sin espejos',     valor: '1,969 mm' },
      { label: 'Altura',                valor: '1,798 mm' },
      { label: 'Distancia entre ejes',  valor: '2,964 mm' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS 4 ruedas',           valor: 'Sí' },
      { label: 'Control de estabilidad',         valor: 'Sí' },
      { label: 'Crucero adaptativo (ACC)',        valor: 'Con Stop & Go' },
      { label: 'Detección colisión frontal',     valor: 'Plus' },
      { label: 'Asistencia en intersección',     valor: 'Sí' },
      { label: 'Frenado peatones/ciclistas',     valor: 'Sí' },
      { label: 'Punto ciego y ruta transversal', valor: 'Sí' },
      { label: 'Visión envolvente 360°',         valor: 'No incluida' },
      { label: 'Advertencia distancia lateral',  valor: 'No incluida' },
      { label: 'Cámara Off-Road integrada',      valor: 'No incluida' },
      { label: 'Visión nocturna',                valor: 'No incluida' },
      { label: 'Asistencia de carril',           valor: 'Sí' },
      { label: 'Reconocimiento de señales',      valor: 'Sí' },
      { label: 'Control descenso en pendientes', valor: 'No incluido' },
      { label: 'Detección de fatiga',            valor: 'No incluida' },
      { label: 'Sensores de estacionamiento',    valor: 'Traseros con función stop' },
      { label: 'Autoestacionamiento',            valor: 'No incluido' },
      { label: 'Acceso pasivo (keyless)',         valor: 'Puertas frontales' },
      { label: 'Freno de estacionamiento',       valor: 'Eléctrico' },
      { label: 'Arranque en pendiente (HSA)',    valor: 'Sí' },
      { label: 'Bolsas de aire',                 valor: '8 (frontales + rodillas + laterales + cortina)' },
      { label: 'Monitor presión neumáticos',     valor: 'Sí' },
      { label: 'Alarma',                         valor: 'Sí' },
    ],
  },
]

const GC_LIMITED: Categoria[] = merge(GC_BASE, {
  desempeno: {
    'Tracción':                  'Quadra-Trac I® (4X4)',
    'Sistema Selec-Terrain®':    'Sí',
    'Diferencial frontal':       'Convencional con eje desconectable',
  },
  interior: {
    'Tapicería':                     'Piel Nappa',
    'Asientos delanteros ventilados':'Sí',
    'Ajuste asiento conductor':      'Eléctrico 8 vías',
    'Memoria asiento conductor':     'Sí',
    'Ajuste asiento pasajero':       'Eléctrico 8 vías',
    'Segunda fila calefactable':     'Sí',
    'Audio':                         '9 altavoces + subwoofer',
    'Amplificador':                  '506 W',
    'Iluminación ambiental':         'LED',
    'Espejo retrovisor interior':    'Electrocrómico digital',
    'Columna dirección con memoria': 'Sí',
    'Control apertura de garage':    'Sí',
  },
  exterior: {
    'Rines':                '20×8.5 negro (diseño Overland)',
    'Techo panorámico':     'Doble panel panorámico',
    'Faros de niebla':      'LED frontales',
    'Espejos señalización': 'Sí',
  },
  seguridad: {
    'Visión envolvente 360°':        'Sistema de visión envolvente 360°',
    'Advertencia distancia lateral': 'Sí',
    'Cámara Off-Road integrada':     'Sí',
    'Sensores de estacionamiento':   'Delanteros y traseros con función stop',
    'Acceso pasivo (keyless)':       '4 puertas y maletero',
  },
})

const GC_LIMITED_L: Categoria[] = merge(GC_LIMITED, {
  interior: {
    'Pasajeros':              '7',
    'Filas de asientos':      '3',
    'Tercera fila':           '50/50 plegable manualmente',
    'Puerto USB 3ª fila':     'Sí',
    'Head-Up Display':        'Sí',
    'Aire acondicionado':     'Automático 3 zonas',
  },
  seguridad: {
    'Visión nocturna': 'Con detección de peatones y animales',
  },
})

const GC_SUMMIT: Categoria[] = merge(GC_LIMITED_L, {
  desempeno: {
    'Tracción':                 'Quadra-Trac II® (4X4 tiempo completo)',
    'Diferencial trasero (LSD)':'Con limitador de deslizamiento',
    'Receptor de remolque':     'Clase IV (cableado 7 y 4 pines)',
    'Suspensión neumática':     'Quadra-Lift® neumática',
  },
  interior: {
    'Tapicería':                     'Piel Palermo',
    'Asientos delanteros con masaje':'Sí',
    'Ajuste asiento conductor':      'Eléctrico 12 vías',
    'Ajuste asiento pasajero':       'Eléctrico 12 vías',
    'Memoria asiento pasajero':      'Sí',
    'Segunda fila ventilada':        'Sí',
    'Segunda fila cortinillas':      'Manuales',
    'Audio':                         '19 altavoces premium',
    'Amplificador':                  '950 W',
    'Iluminación ambiental':         'LED multicolor',
    'Iluminación cortesía puertas':  'Sí',
    'Pantalla interactiva pasajero': 'Sí',
    'Visualiz. de mapas en clúster': 'Sí',
    'Aire acondicionado':            'Automático 4 zonas',
    'Volante':                       'Piel',
  },
  exterior: {
    'Neumáticos':      '275/45R21XL All Season',
    'Rines':           '21×9.0 maquinados',
    'Exterior bitono': 'Sí',
    'Espejos plegado': 'Eléctrico',
    'Maletero':        'Eléctrico con manos libres (pie)',
  },
  seguridad: {
    'Control descenso en pendientes': 'Sí',
    'Detección de fatiga':            'Sí',
    'Autoestacionamiento':            'Paralelo y perpendicular con función stop',
  },
})

// ─────────────────────────────────────────────────────────────────────────────
// JEEP COMMANDER OVERLAND  2025 / 2026
// ─────────────────────────────────────────────────────────────────────────────

const COMMANDER_BASE_CATS = (v: '2025' | '2026'): Categoria[] => [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                  valor: v === '2025' ? 'Turbo 1.3L 4 cilindros con Start & Stop' : '1.3 L Turbo' },
      { label: 'Potencia',               valor: '173 hp @ 5,750 rpm' },
      { label: 'Torque',                 valor: '199 lb-ft @ 1,850 rpm' },
      { label: 'Transmisión',            valor: v === '2025' ? 'Automática 6 vel. AutoStick®' : 'Automática 6 vel. Aisin Gen3 + paletas' },
      { label: 'Tracción',               valor: 'FWD' },
      { label: 'Suspensión',             valor: 'McPherson delantera y trasera' },
      { label: 'Capacidad de carga',     valor: v === '2025' ? '400 kg' : '540 kg' },
      { label: 'Capacidad de arrastre',  valor: '400 kg' },
      { label: 'Peso bruto vehicular',   valor: '2,255 kg' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',               valor: v === '2025' ? 'Piel Nappa Premium y gamuza café' : 'Piel Brown Commander' },
      { label: 'Pasajeros',               valor: '7' },
      { label: 'Asientos delanteros',     valor: v === '2025' ? 'Eléctricos 8 vías' : 'Eléctricos 8 vías con memoria' },
      { label: 'Pantalla principal',      valor: v === '2025' ? 'Uconnect® 10.1" + Clúster 10.25"' : 'Infoentretenimiento 10.1"' },
      { label: 'Audio',                   valor: v === '2025' ? 'Harman Kardon® 9 bocinas + Subwoofer' : 'Sistema de audio premium' },
      { label: 'Carga inalámbrica',       valor: 'Sí' },
      { label: 'Quemacocos',              valor: v === '2025' ? 'Dual panorámico CommandView®' : 'Eléctrico' },
      { label: 'Apple CarPlay / Android Auto', valor: v === '2025' ? 'Inalámbrico' : 'No especificado' },
      { label: 'Aire acondicionado',      valor: v === '2025' ? 'Automático bizona' : 'Sistema de A/C' },
      { label: 'Cajuela',                 valor: v === '2025' ? '661 L + hasta 1,760 L (filas abatidas)' : '661 L' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Rines',                valor: v === '2025' ? 'Aluminio 19" Pirelli 235/50 R19' : 'Overland 19" — 235/50 R19' },
      { label: 'Techo',                valor: 'Bitono negro' },
      { label: 'Maletero',             valor: v === '2025' ? 'Eléctrico con manos libres (pie)' : 'Eléctrico con manos libres' },
      { label: 'Luces delanteras',     valor: 'LED automáticas' },
      { label: 'Luces traseras',       valor: 'LED' },
      { label: 'Faros de niebla',      valor: 'LED' },
      { label: 'Longitud',             valor: '4,769 mm' },
      { label: 'Ancho sin espejos',    valor: '1,859 mm' },
      { label: 'Altura',               valor: '1,685 mm' },
      { label: 'Distancia entre ejes', valor: '2,794 mm' },
      { label: 'Colores exteriores',   valor: v === '2025' ? 'Negro carbón, Plata martillado, Blanco polar, Gris granito, Slash gold' : 'Negro, Plata metálico, Granito cristal, Slash gold' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',                    valor: 'Sí' },
      { label: 'Control de estabilidad',         valor: v === '2025' ? 'ESC' : 'VDC' },
      { label: 'Crucero adaptativo (ACC)',        valor: v === '2025' ? 'Con Stop & Go' : 'Sí' },
      { label: 'Punto ciego',                    valor: v === '2025' ? 'BSCPD (con ruta transversal de reversa)' : 'Monitoreo de punto ciego' },
      { label: 'Visión 360°',                    valor: v === '2025' ? 'No incluida' : 'Sistema de visión 360°' },
      { label: 'Asistencia de carril',           valor: v === '2025' ? 'Lane Departure Plus' : 'Asistencia de mantenimiento y cambio de carril' },
      { label: 'Reconocimiento de señales',      valor: v === '2025' ? 'Sí' : 'Sí' },
      { label: 'Detección colisión frontal',     valor: v === '2025' ? 'Plus (con peatones y ciclistas)' : 'Plus FWD' },
      { label: 'Control tracción All Speed',     valor: v === '2025' ? 'Sí' : 'Sí + TC+' },
      { label: 'Freno Hill Holder',              valor: v === '2025' ? 'HSA' : 'Hill Holder + Auto Hold' },
      { label: 'Limitador de velocidad activo',  valor: v === '2025' ? 'No especificado' : 'Sí' },
      { label: 'ISOFIX',                         valor: 'Sí' },
      { label: 'Autoestacionamiento',            valor: 'Paralelo y perpendicular' },
      { label: 'Monitor presión neumáticos',     valor: 'Sí' },
    ],
  },
]

// ── Jeep Compass 2026 ────────────────────────────────────────────────────────

const COMPASS_2026_LIMITED_PREMIUM: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                 valor: '1.3 L Turbo' },
      { label: 'Potencia',              valor: '173 hp @5,750 rpm' },
      { label: 'Torque',                valor: '199 lb-pie @1,850 rpm' },
      { label: 'Tanque de combustible', valor: '60 L gasolina' },
      { label: 'Tecnología',            valor: 'Start & Stop – ESS' },
      { label: 'Arranque remoto',       valor: 'Sí' },
      { label: 'Transmisión',           valor: 'Automática 6 velocidades' },
      { label: 'Tracción',              valor: 'Delantera FWD' },
      { label: 'Caja de transferencia', valor: 'No aplica (FWD)' },
      { label: 'Sistema Selec Terrain', valor: 'No incluido' },
      { label: 'Paletas al volante',    valor: 'Sí' },
      { label: 'Columna de dirección',  valor: 'Ajustable' },
      { label: 'Dirección',             valor: 'Eléctrica' },
      { label: 'Diámetro de giro',      valor: '11.3 m' },
      { label: 'Toma auxiliar',         valor: '12 V' },
      { label: 'Suspensión',            valor: 'McPherson, ruedas independientes + barra estabilizadora' },
      { label: 'Ángulos off-road',      valor: 'Entrada 21.5° | ventral 20.5° | salida 30.7°' },
      { label: 'Capacidad de carga',    valor: '400 kg' },
      { label: 'Capacidad de arrastre', valor: '400 kg' },
      { label: 'Maletero',              valor: '476 L | 1,180 L asiento abatido' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',              valor: 'Piel Black' },
      { label: 'Asiento conductor',      valor: 'Manual 6 vías' },
      { label: 'Ajuste lumbar conductor',valor: '—' },
      { label: 'Asiento pasajero',       valor: 'Manual 4 vías' },
      { label: 'Cristales',              valor: 'Eléctricos' },
      { label: 'Desempañante trasero',   valor: 'Sí' },
      { label: 'Pantalla táctil',        valor: '10.1"' },
      { label: 'Clúster',                valor: '—' },
      { label: 'Audio',                  valor: '6 altavoces – Beats' },
      { label: 'Carga inalámbrica',      valor: 'Sí' },
      { label: 'Conectividad',           valor: 'USB Tipo A-C' },
      { label: 'USB 2ª fila',            valor: 'Tipo A, C' },
      { label: 'Consola frontal',        valor: 'Sí' },
      { label: 'Descansabrazos frontal', valor: 'Sí' },
      { label: 'Descansabrazos trasero', valor: 'Sí' },
      { label: 'Volante',                valor: 'Forrado en piel' },
      { label: 'A/C',                    valor: 'Sí' },
      { label: 'Sistema purificación aire', valor: '—' },
      { label: 'Ventilas 2ª fila',       valor: '—' },
      { label: 'Cubierta maletero',      valor: 'Desmontable' },
      { label: 'Ganchos maletero',       valor: 'Sí' },
      { label: '2ª fila',                valor: '60/40 plegable' },
      { label: 'Reposacabezas traseros', valor: '3 pasajeros' },
      { label: 'Tapetes',                valor: 'Frontales/traseros' },
      { label: 'Espejo retrovisor',      valor: 'Día/noche manual' },
      { label: 'Iluminación lectura',    valor: 'Frontal/trasero' },
      { label: 'Iluminación ambiental',  valor: 'LED' },
      { label: 'Iluminación maletero',   valor: 'De cortesía' },
      { label: 'Quemacocos',             valor: 'Eléctrico' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Iluminación frontal',         valor: 'LED automática' },
      { label: 'Iluminación diurna LED',      valor: '—' },
      { label: 'Faros de niebla',             valor: 'LED' },
      { label: 'Entrada con cortesía',        valor: 'Sí' },
      { label: 'Espejos laterales',           valor: 'Abatibles manualmente, negro' },
      { label: 'Cambio de luces inteligente', valor: '—' },
      { label: 'Limpiador medallón',          valor: 'Sí' },
      { label: 'Manijas',                     valor: 'Al color de la carrocería' },
      { label: 'Barras de toldo',             valor: 'Black' },
      { label: 'Rines',                       valor: 'Aluminio 18"' },
      { label: 'Neumáticos',                  valor: '225/55R18' },
      { label: 'Techo',                       valor: 'Al color de la carrocería' },
      { label: 'Cristales con tinte profundo',valor: '—' },
      { label: 'Puerta de maletero',          valor: '—' },
      { label: 'Open & Go',                   valor: '—' },
      { label: 'Peso vehicular',              valor: '1,557 kg' },
      { label: 'Peso bruto',                  valor: '1,957 kg' },
      { label: 'Longitud',                    valor: '4,404 mm' },
      { label: 'Ancho',                       valor: '1,819 mm' },
      { label: 'Altura',                      valor: '1,625 mm' },
      { label: 'Distancia entre ejes',        valor: '2,636 mm' },
      { label: 'Colores disponibles',         valor: 'Negro Diamante, Blanco Polar, Gris Granito, Azul Jazz' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',                   valor: 'Disco frontal/trasero' },
      { label: 'Freno de estacionamiento',      valor: 'Eléctrico' },
      { label: 'Arranque en pendientes (HSA)',  valor: 'Sí' },
      { label: 'Control de tracción (TC+)',     valor: 'Sí' },
      { label: 'Cámara de reversa',             valor: 'Sí' },
      { label: 'Control dinámico (VDC)',        valor: 'Sí' },
      { label: 'Control crucero',               valor: 'Sí' },
      { label: 'Control de tracción All Speed', valor: 'Sí' },
      { label: 'Control anti vuelco',           valor: 'Sí' },
      { label: 'Asistencia balanceo remolque',  valor: 'Sí' },
      { label: 'Auto Hold',                     valor: 'Sí' },
      { label: 'Limitador de velocidad',        valor: 'Sí' },
      { label: 'Luces traseras adaptativas',    valor: 'Sí' },
      { label: 'Cierre centralizado',           valor: 'Sí' },
      { label: 'Cinturones traseros',           valor: 'Con retractor' },
      { label: 'Sensor de lluvia',              valor: 'Sí' },
      { label: 'Bolsas de aire frontal',        valor: 'Conductor/pasajero' },
      { label: 'Bolsas de aire laterales',      valor: 'Asiento' },
      { label: 'Bolsa de aire cortina',         valor: 'Sí' },
      { label: 'Bolsa rodillas conductor',      valor: '—' },
      { label: 'Asistencia estacionamiento',    valor: 'Paralelo y perpendicular' },
      { label: 'Sensores estacionamiento',      valor: 'Sí' },
      { label: 'TPMS',                          valor: 'Sí' },
      { label: 'Smart Key',                     valor: 'Sí' },
      { label: 'Acceso pasivo',                 valor: '—' },
      { label: 'Clasificación de ocupantes',    valor: 'Sí' },
      { label: 'ISOFIX',                        valor: 'Sí' },
      { label: 'Alerta cinturones',             valor: 'Delanteros/traseros' },
      { label: 'Refacción',                     valor: 'Tamaño convencional' },
      { label: 'Alarma',                        valor: 'Sí' },
      { label: 'Colisión frontal (Full Speed)',  valor: '—' },
      { label: 'Mantenimiento de carril',        valor: '—' },
      { label: 'Señales de tránsito',           valor: '—' },
      { label: 'Detección de fatiga',           valor: '—' },
      { label: 'Frenado emergencia peatón',     valor: '—' },
      { label: 'Monitor punto ciego',           valor: '—' },
    ],
  },
]

const COMPASS_2026_ALTITUDE: Categoria[] = merge(COMPASS_2026_LIMITED_PREMIUM, {
  desempeno: {
    'Ángulos off-road': 'Entrada 20.6° | ventral 20.1° | salida 30.8°',
  },
  interior: {
    'Asiento conductor': 'Eléctrico 8 vías',
    'Clúster':           'TFT 10.25"',
    'Espejo retrovisor': 'Electrocrómico',
  },
  exterior: {
    'Espejos laterales':           'Plegables eléctricamente, con memoria e iluminación de cortesía',
    'Cambio de luces inteligente': 'Sí',
    'Rines':                       'Aluminio 19"',
    'Neumáticos':                  '235/45R19',
    'Techo':                       'Negro – bitono',
    'Peso vehicular':              '1,566 kg',
    'Peso bruto':                  '1,966 kg',
  },
  seguridad: {
    'Control crucero':             'Adaptativo (ACC)',
    'Colisión frontal (Full Speed)':'Sí',
    'Mantenimiento de carril':     'Sí',
    'Señales de tránsito':         'Sí',
    'Detección de fatiga':         'Sí',
    'Frenado emergencia peatón':   'Sí',
    'Monitor punto ciego':         'Sí',
  },
})

const COMPASS_2026_HIGH_ALTITUDE: Categoria[] = merge(COMPASS_2026_ALTITUDE, {
  desempeno: {
    'Motor':                  '2.0L I4 DOHC DI Turbo',
    'Potencia':                '200 hp @ 5,000 rpm',
    'Torque':                  '221 lb-pie @ 1,750 rpm',
    'Transmisión':             'Automática 8 velocidades 8F30',
    'Tracción':                'AWD',
    'Diámetro de giro':        '15.7 m',
    'Suspensión':              'Delantera McPherson; trasera Chapman con eslabones de acero, resortes helicoidales + barra estabilizadora',
    'Ángulos off-road':        'Entrada 16.1° | ventral 22.6° | salida 31.4°',
    'Capacidad de carga':      '466 kg',
    'Capacidad de arrastre':   '908 kg',
    'Caja de transferencia':   'Active Drive Full Time 4x4',
    'Sistema Selec Terrain':   'Sí',
  },
  interior: {
    'Tapicería':                  'Piel',
    'Asiento pasajero':           'Manual 6 vías',
    'Pantalla táctil':            '10.1" Uconnect 5 con GPS',
    'A/C':                        'Automático doble zona',
    'Audio':                      'Premium Alpine',
    'Consola frontal':            'Deslizable con descansabrazos',
    'Descansabrazos trasero':     'Con porta vasos',
    'Quemacocos':                 'Techo panorámico',
    'Ajuste lumbar conductor':    'Eléctrico 2 vías',
    'Sistema purificación aire':  'Sí (Jeep®)',
    'Ventilas 2ª fila':           'Sí',
  },
  exterior: {
    'Espejos laterales':            'Plegables manualmente, ajuste eléctrico, calefactables, con indicadores',
    'Peso vehicular':               '1,711 kg',
    'Peso bruto':                   '2,177 kg',
    'Ancho':                        '1,874 mm',
    'Altura':                       '1,647 mm',
    'Colores disponibles':          'Plata Metálico, Negro Diamante, Blanco Brillante',
    'Iluminación diurna LED':       'Sí',
    'Cristales con tinte profundo': 'Sí',
    'Puerta de maletero':           'Eléctrica con activación con pie',
    'Open & Go':                    'Sí',
  },
  seguridad: {
    'Bolsa rodillas conductor': 'Sí',
    'Acceso pasivo':            'Puertas frontales',
  },
})

// ── Jeep Cherokee Híbrido 2026 ───────────────────────────────────────────────

const CHEROKEE_HIBRIDO_LIMITED: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Sistema híbrido',              valor: '3 motores' },
      { label: 'Potencia combinada',           valor: '210 hp' },
      { label: 'Torque combinado',             valor: '230 lb-ft' },
      { label: 'Motor',                        valor: '4 cilindros en línea, 1.6 L Turbo Hybrid DI' },
      { label: 'Transmisión',                  valor: 'Híbrida BN EVT313 continuamente variable' },
      { label: 'Batería principal',            valor: '550 A, libre de mantenimiento' },
      { label: 'Batería iones de litio',       valor: '400 V, 1.08 kWh' },
      { label: 'Frenos regenerativos',         valor: 'Sí' },
      { label: 'Tracción',                     valor: '4x4 Jeep Active Drive I' },
      { label: 'Caja de transferencia',        valor: 'Una velocidad, con desconexión de eje trasero' },
      { label: 'Diferencial trasero',          valor: 'Convencional' },
      { label: 'Sistema Selec-Terrain®',       valor: 'Sí' },
      { label: 'Parrilla persianas activas',   valor: 'Sí' },
      { label: 'Persianas activas secundarias',valor: 'Sí' },
      { label: 'Encendido remoto',             valor: 'Sí' },
      { label: 'Tanque de combustible',        valor: '51.8 L' },
      { label: 'Dirección',                    valor: 'Electroasistida, piñón y cremallera' },
      { label: 'Suspensión delantera',         valor: 'McPherson' },
      { label: 'Suspensión trasera',           valor: 'Integral Link' },
      { label: 'Rendimiento combinado',        valor: '15.73 km/L' },
    ],
  },
  {
    id: 'dimensiones', nombre: 'Dimensiones y Capacidades', specs: [
      { label: 'Largo total',                  valor: '4,778 mm' },
      { label: 'Ancho sin espejos',            valor: '1,898 mm' },
      { label: 'Ancho con espejos',            valor: '2,123 mm' },
      { label: 'Alto',                         valor: '1,715 mm' },
      { label: 'Distancia entre ejes',         valor: '2,869 mm' },
      { label: 'Ángulo de entrada',            valor: '19.6°' },
      { label: 'Ángulo ventral',               valor: '18.8°' },
      { label: 'Ángulo de salida',             valor: '29.4°' },
      { label: 'Capacidad de vadeo',           valor: '50.8 cm' },
      { label: 'Peso vehicular',               valor: '1,945 kg' },
      { label: 'Peso bruto vehicular',         valor: '2,426 kg' },
      { label: 'Capacidad de carga',           valor: '385 kg' },
      { label: 'Capacidad de arrastre',        valor: '1,587 kg' },
      { label: 'Volumen carga (2ª fila)',      valor: '951 L' },
      { label: 'Volumen carga (2ª abatida)',   valor: '1,934 L' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Rines',                            valor: 'Aluminio 18", maquinado/pintado' },
      { label: 'Neumáticos',                       valor: '225/60R18 BSW A/S' },
      { label: 'Llanta de refacción',              valor: 'Compacta' },
      { label: 'Faros',                            valor: 'Reflectores LED' },
      { label: 'Encendido automático de faros',    valor: 'Sí' },
      { label: 'Apagado faros con retardo',        valor: 'Sí' },
      { label: 'Control automático luces altas',   valor: 'Sí' },
      { label: 'Luces diurnas (DRL)',              valor: 'LED' },
      { label: 'Faros de niebla',                  valor: 'LED' },
      { label: 'Lámparas traseras',                valor: 'LED' },
      { label: 'Fascias',                          valor: 'Al color con acentos off-road' },
      { label: 'Biseles D fascia inferior',        valor: 'Sí' },
      { label: 'Parrilla',                         valor: 'Jeep con acento negro brillante' },
      { label: 'Antena',                           valor: 'Tipo aleta de tiburón en accent color' },
      { label: 'Arcos de rueda',                   valor: 'Off-road' },
      { label: 'Manijas exteriores',               valor: 'Empotradas al color de la carrocería' },
      { label: 'Espejos exteriores',               valor: 'Eléctricos, abatibles, calefactables' },
      { label: 'Detalle espejos',                  valor: 'Negro brillante, con direccionales y luces de cortesía' },
      { label: 'Espejo conductor electrocrómico',  valor: 'No incluido' },
      { label: 'Limpiaparabrisas con deshielo',    valor: 'No incluido' },
      { label: 'Quemacocos',                       valor: 'Dual panorámico CommandView®' },
      { label: 'Parabrisas acústico',              valor: 'Sí' },
      { label: 'Sensor de lluvia',                 valor: 'Sí' },
      { label: 'Cristales traseros',               valor: 'De privacidad' },
      { label: 'Medallón trasero',                 valor: 'Con limpiador y desempañante' },
      { label: 'Rieles de techo',                  valor: 'Sí' },
      { label: 'Techo bitono',                     valor: 'No incluido' },
      { label: 'Compuerta trasera',                valor: 'Eléctrica' },
      { label: 'Seguro compuerta combustible',     valor: 'Eléctrico' },
      { label: 'Salida de escape',                 valor: 'Oculta' },
      { label: 'Tratamiento aerodinámico inferior',valor: 'Sí' },
      { label: 'Emblema',                          valor: 'Limited' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Pasajeros',                       valor: '5' },
      { label: 'Clúster',                         valor: 'Pantalla a color 10.25"' },
      { label: 'A/C',                             valor: 'Automático 2 zonas' },
      { label: 'Filtro A/C',                      valor: 'N95+Bio' },
      { label: 'Sensor de humedad',               valor: 'Sí' },
      { label: 'Tapicería',                       valor: 'Leatherette Capri perforado' },
      { label: 'Costuras interiores',             valor: 'Acentuadas en coñac' },
      { label: 'Asiento conductor',               valor: 'Eléctrico 8 vías' },
      { label: 'Asiento pasajero',                valor: 'Eléctrico 6 vías' },
      { label: 'Ajuste lumbar delanteros',        valor: 'Eléctrico 2 vías' },
      { label: 'Cabeceras delanteras',            valor: 'Ajuste 2 vías' },
      { label: 'Asientos delanteros calefactables',valor: 'Sí' },
      { label: 'Asientos delanteros ventilados',  valor: 'No incluidos' },
      { label: 'Asientos 2ª fila calefactables',  valor: 'No incluidos' },
      { label: 'Paneles de puerta',               valor: 'Revestimiento de lujo' },
      { label: 'Portamapas en respaldo',          valor: 'Sí' },
      { label: '2ª fila',                         valor: '60/40 abatible' },
      { label: 'Cabeceras 2ª fila',               valor: '3' },
      { label: 'Acentos interiores',              valor: 'Cromo satinado plateado' },
      { label: 'Descansabrazos trasero',          valor: 'Con portavasos' },
      { label: 'Volante',                         valor: 'Premium con controles de audio' },
      { label: 'Volante calefactable',            valor: 'Sí, con ajuste de altura y profundidad' },
      { label: 'Consola de piso',                 valor: 'Tamaño completo con contenedor ocultable' },
      { label: 'Salidas A/C 2ª fila',             valor: 'Sí (consola central)' },
      { label: 'Mini consola de techo',           valor: 'Sí' },
      { label: 'Tapetes',                         valor: 'De piso' },
      { label: 'Luces interiores',                valor: 'Lectura del/tras + mapa + cortesía' },
      { label: 'Entrada iluminada',               valor: 'Sí' },
      { label: 'Cristales',                       valor: 'Eléctricos one-touch arriba y abajo' },
      { label: 'Entrada pasiva',                  valor: '4 puertas' },
      { label: 'Encendido',                       valor: 'Botón Enter & Go®' },
      { label: 'Seguros eléctricos',              valor: 'Sensibles a la velocidad' },
      { label: 'Tomacorrientes 12V',              valor: '2 auxiliares' },
      { label: 'Iluminación de carga',            valor: 'LED + arillos de anclaje' },
      { label: 'Asideras de pasajero',            valor: 'Sí' },
      { label: 'Viseras',                         valor: 'Con espejos de vanidad iluminados' },
      { label: 'Pantalla principal',              valor: 'Uconnect® 5 — 12.3" táctil' },
      { label: 'Apple CarPlay / Android Auto',    valor: 'Inalámbrico' },
      { label: 'Audio',                           valor: '6 altavoces' },
      { label: 'Cancelación activa de ruido',     valor: 'Sí' },
      { label: 'USB delanteros',                  valor: 'Tipo C funcionalidad total' },
      { label: 'USB traseros',                    valor: 'Tipo C solo carga' },
      { label: 'Manos libres',                    valor: 'Bluetooth teléfono y audio' },
      { label: 'Cargador inalámbrico',            valor: 'Sí' },
      { label: 'Espejo retrovisor',               valor: 'Electrocrómico' },
      { label: 'Control universal de garage',     valor: 'Sí' },
      { label: 'Radio HD',                        valor: 'No incluido' },
      { label: 'Navegación GPS',                  valor: 'No incluida' },
      { label: 'Off Road Pages',                  valor: 'No incluido' },
      { label: 'Proyección mapas en clúster',     valor: 'No incluida' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Alarma de seguridad',                  valor: 'Sí' },
      { label: 'Bolsas de aire frontales',             valor: 'Avanzadas multietapas' },
      { label: 'Clasificación de ocupante',            valor: 'Sí' },
      { label: 'Bolsa rodillas conductor',             valor: 'Sí' },
      { label: 'Bolsas laterales delanteras',          valor: 'Sí' },
      { label: 'Bolsas cortina',                       valor: 'Delanteras y traseras' },
      { label: 'Bolsas laterales traseras',            valor: 'Sí' },
      { label: 'Cinturones delanteros',                valor: 'Con ajuste de altura' },
      { label: 'Active Drive Assist L2',               valor: 'Sí (mantenimiento de carril)' },
      { label: 'Gestión activa de carril',             valor: 'Sí' },
      { label: 'Crucero adaptativo (ACC)',             valor: 'Con Stop & Go' },
      { label: 'ACC caminos rudos',                    valor: 'Sí' },
      { label: 'Control de tracción (TCS)',            valor: 'A cualquier velocidad' },
      { label: 'Alerta colisión frontal',              valor: 'Plus' },
      { label: 'Asistencia avanzada de frenado',       valor: 'Sí' },
      { label: 'Frenado emergencia peat./cicl.',       valor: 'Sí' },
      { label: 'Punto ciego y ruta transversal',       valor: 'Sí' },
      { label: 'Alerta de rebase a alta velocidad',    valor: 'Sí' },
      { label: 'Detección de fatiga',                  valor: 'Sí' },
      { label: 'Colisión en intersección',             valor: 'Sí' },
      { label: 'Alerta acústica EV (AVAS)',            valor: 'Sí' },
      { label: 'ParkSense® trasero',                   valor: 'Con stop' },
      { label: 'Cámara ParkView®',                     valor: 'Con guías activas' },
      { label: 'Sistema EARS',                         valor: 'Respuesta mejorada en accidentes' },
      { label: 'Control de estabilidad (ESC)',         valor: 'Sí' },
      { label: 'Mitigación anti-vuelco (ERM)',         valor: 'Sí' },
      { label: 'Arranque en pendiente (HSA)',          valor: 'Sí' },
      { label: 'Estabilidad para remolques (TSD)',     valor: 'Sí' },
      { label: 'Frenos disco 4 ruedas con ABS',        valor: 'Sí' },
      { label: 'Freno de estacionamiento',             valor: 'Electrónico' },
      { label: 'Alistamiento de frenos (RAB)',         valor: 'Sí' },
      { label: 'Retención del vehículo Hold ‘n Go',    valor: 'Sí' },
      { label: 'Alerta de ocupante trasero',           valor: 'Sí' },
      { label: 'TPMS',                                 valor: 'Sí' },
      { label: 'Alerta llenado de neumáticos',         valor: 'Seleccionable' },
      { label: 'LATCH',                                valor: 'Sí' },
      { label: 'Protección anti-descarga batería',     valor: 'Sí' },
      { label: 'Reconocimiento de señales',            valor: 'No incluido' },
      { label: 'Visión 360°',                          valor: 'No incluida' },
      { label: 'Sistema lava-cámara',                  valor: 'No incluido' },
      { label: 'Advertencia distancia lateral',        valor: 'No incluida' },
      { label: 'ParkSense® estacionamiento automatiz.',valor: 'No incluido' },
    ],
  },
]

const CHEROKEE_HIBRIDO_OVERLAND: Categoria[] = merge(CHEROKEE_HIBRIDO_LIMITED, {
  exterior: {
    'Rines':                          'Aluminio 20", maquinado/pintado',
    'Neumáticos':                     '235/50R20XL Pirelli A/S Performance',
    'Espejo conductor electrocrómico':'Sí',
    'Limpiaparabrisas con deshielo':  'Sí',
    'Techo bitono':                   'Negro',
    'Compuerta trasera':              'Eléctrica con apertura manos libres',
    'Emblema':                        'Overland',
  },
  interior: {
    'Tapicería':                   'Leatherette Capri perforada — diseño especial',
    'Asientos delanteros ventilados':'Sí',
    'Asientos 2ª fila calefactables':'Sí',
    'Radio HD':                    'Sí (alta definición)',
    'Navegación GPS':              'Sí',
    'Off Road Pages':              'Sí',
    'Audio':                       'Premium Alpine — 9 altavoces amplificados + subwoofer',
    'Proyección mapas en clúster': 'Sí',
    'Espejo retrovisor':           'Electrocrómico con pantalla digital',
  },
  seguridad: {
    'Reconocimiento de señales':            'Sí',
    'Visión 360°':                          'Sí (mediante cámaras)',
    'Sistema lava-cámara':                  'Delantera y trasera',
    'Advertencia distancia lateral':        'Sí',
    'ParkSense® estacionamiento automatiz.':'Sí',
  },
})

// ── Jeep Grand Wagoneer L 2026 ───────────────────────────────────────────────

const GRAND_WAGONEER_L_LIMITED: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                          valor: '3.0 L I6 Hurricane Twin Turbo ESS' },
      { label: 'Potencia',                       valor: '420 hp @ 5,200 rpm' },
      { label: 'Torque',                         valor: '469 lb-ft @ 3,500 rpm' },
      { label: 'Arranque remoto',                valor: 'Sí' },
      { label: 'Transmisión',                    valor: 'Automática 8 velocidades 880RE' },
      { label: 'Caja de transferencia',          valor: 'On Demand' },
      { label: 'Relación de eje trasero',        valor: '3.55' },
      { label: 'Diferencial trasero',            valor: 'Antideslizamiento' },
      { label: 'Eje delantero',                  valor: 'Desconectable' },
      { label: 'Páginas Off-Road',               valor: 'Sí' },
      { label: 'Sistema Selec-Terrain®',         valor: 'Sí' },
      { label: 'Alternador',                     valor: '230 A' },
      { label: 'Batería',                        valor: '700 A libre de mantenimiento' },
      { label: 'Batería auxiliar',               valor: 'Sí' },
      { label: 'Inversor de potencia',           valor: '150 W' },
      { label: 'Salida 12V delantera',           valor: 'Sí' },
      { label: 'Salida 12V trasera',             valor: 'Sí' },
      { label: 'Salida 115V auxiliar',           valor: 'Sí' },
      { label: 'Columna de dirección con memoria',valor: 'Sí' },
      { label: 'Dirección',                      valor: 'Eléctrica' },
      { label: 'Suspensión',                     valor: 'Neumática Quadra-Lift®' },
      { label: 'Cableado de remolque',           valor: '4 y 7 pines' },
      { label: 'Receptor de remolque',           valor: 'Clase IV' },
      { label: 'Volumen interior',               valor: '4.9 m³' },
      { label: 'Volumen de maletero',            valor: '1.3 m³' },
      { label: 'Volumen máximo de carga',        valor: '3.2 m³' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',                       valor: 'Piel negra' },
      { label: 'Pasajeros',                       valor: '7' },
      { label: 'Asientos delanteros ventilados',  valor: 'Sí' },
      { label: 'Asientos delanteros calefactables',valor: 'Sí' },
      { label: 'Ajuste lumbar delanteros',        valor: 'Eléctrico 4 vías' },
      { label: 'Ajuste asientos delanteros',      valor: 'Eléctrico 8 vías' },
      { label: 'Memoria asiento conductor',       valor: 'Sí' },
      { label: '2ª fila calefactables',           valor: 'Sí' },
      { label: '2ª fila',                         valor: 'Capitán reclinables' },
      { label: '3ª fila',                         valor: 'Reclinable 60/40' },
      { label: 'Tapete maletero',                 valor: 'Reversible (vinil/alfombrilla)' },
      { label: 'Ganchos maletero',                valor: 'Sí' },
      { label: 'Tapetes',                         valor: 'Premium delanteros y traseros' },
      { label: 'Cortinillas 2ª fila',             valor: 'Manuales' },
      { label: 'Desempañador trasero',            valor: 'Sí' },
      { label: 'Parasol',                         valor: 'Con iluminación y espejo de vanidad' },
      { label: 'Espejo retrovisor',               valor: 'Electrocrómico' },
      { label: 'A/C',                             valor: 'Automático 3 zonas' },
      { label: 'Clúster',                         valor: 'TFT a color 12"' },
      { label: 'Guantera de seguridad',           valor: 'Sí' },
      { label: 'Navegación GPS',                  valor: 'Sí' },
      { label: 'Memoria en radio',                valor: 'Sí' },
      { label: 'Control activo de ruido',         valor: 'Sí' },
      { label: 'Iluminación ambiental',           valor: 'LED' },
      { label: 'Volante calefactable',            valor: 'Sí' },
      { label: 'Volante',                         valor: 'Tecnopiel' },
      { label: 'Audio',                           valor: 'McIntosh® Premium — 19 altavoces' },
      { label: 'Controles de audio al volante',   valor: 'Sí' },
      { label: 'Apple CarPlay / Android Auto',    valor: 'Sí' },
      { label: 'Pantalla táctil',                 valor: 'Uconnect® 12"' },
      { label: 'Pantallas video 2ª fila',         valor: 'Amazon Fire TV®' },
      { label: 'Cargador inalámbrico',            valor: 'Sí' },
      { label: 'USB 2ª fila',                     valor: 'Conector de carga' },
      { label: 'USB centro de medios',            valor: '2 puertos + auxiliar' },
      { label: 'Puerto USB de video',             valor: 'Sí' },
      { label: 'Control universal de garage',     valor: 'Sí' },
      { label: 'Visión de ocupantes',             valor: 'Sí' },
      { label: 'Comando de voz',                  valor: 'Inalámbrico' },
      { label: 'Head-Up Display',                 valor: 'Sí (en parabrisas)' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Parrilla',                         valor: '7 barras con iluminación LED' },
      { label: 'Parrilla frontal',                 valor: 'Negro brillante' },
      { label: 'Iluminación frontal',              valor: 'LED automática' },
      { label: 'Control luces altas automático',   valor: 'Sí' },
      { label: 'Luces diurnas (DRL)',              valor: 'LED' },
      { label: 'Acentos exteriores',               valor: 'Negro' },
      { label: 'Neumáticos',                       valor: '285/45R22XL BSW All Season' },
      { label: 'Rines',                            valor: '22×9.0 negro brillante' },
      { label: 'Parabrisas acústico',              valor: 'Sí' },
      { label: 'Cristales laminados',              valor: 'Sí' },
      { label: 'Cristales con tinte profundo',     valor: 'Sí (contra sol)' },
      { label: 'Espejo conductor electrocrómico',  valor: 'Sí' },
      { label: 'Espejos laterales',                valor: 'Plegables eléctricos, calefactables, negro brillante' },
      { label: 'Espejos con señalización',         valor: 'Sí' },
      { label: 'Espejos con memoria',              valor: 'Sí' },
      { label: 'Espejos autoajuste en reversa',    valor: 'Sí' },
      { label: 'Techo panorámico',                 valor: '3 paneles' },
      { label: 'Compuerta trasera',                valor: 'Manos libres' },
      { label: 'Iluminación de acceso',            valor: 'De cortesía' },
      { label: 'Iluminación de cortesía en manijas',valor: 'Sí' },
      { label: 'Iluminación trasera',              valor: 'LED' },
      { label: 'Manijas exteriores',               valor: 'Al color de la carrocería' },
      { label: 'Estribos laterales',               valor: 'Eléctricos' },
      { label: 'Longitud',                         valor: '5,759 mm' },
      { label: 'Ancho',                            valor: '2,124 mm' },
      { label: 'Altura',                           valor: '2,023 mm' },
      { label: 'Distancia entre ejes',             valor: '3,303 mm' },
      { label: 'Colores disponibles',              valor: 'Plata Zynith, Negro High Gloss, Blanco Brillante, Gris Báltico' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',                          valor: 'Disco en 4 ruedas' },
      { label: 'Asistencia avanzada de frenos',       valor: 'Sí' },
      { label: 'Asistencia de frenos en lluvia',      valor: 'Sí' },
      { label: 'Control de estabilidad (ESC)',        valor: 'Sí' },
      { label: 'Arranque en pendiente (HSA)',         valor: 'Sí' },
      { label: 'Bolsa frontal multietapas',           valor: 'Sí' },
      { label: 'Bolsa lateral complementaria',        valor: 'Sí' },
      { label: 'Bolsa cortina complementaria',        valor: 'Sí' },
      { label: 'ISOFIX',                              valor: 'Sí' },
      { label: 'Cinturones delanteros',               valor: 'Con ajuste de altura' },
      { label: 'Aviso cinturones traseros',           valor: 'Sí' },
      { label: 'Acceso pasivo',                      valor: '4 puertas laterales' },
      { label: 'Sensor de lluvia',                    valor: 'Sí' },
      { label: 'Lavador de cámara trasera',           valor: 'Sí' },
      { label: 'Seguros eléctricos',                  valor: 'Sensibles a la velocidad' },
      { label: 'Aviso al inflado de neumáticos',      valor: 'Sí' },
      { label: 'Alarma de seguridad',                 valor: 'Sí' },
      { label: 'Detección peatones/ciclistas',        valor: 'Sí' },
      { label: 'Colisión frontal plus',               valor: 'Sí' },
      { label: 'Crucero adaptativo (ACC)',            valor: 'Con Stop & Go' },
      { label: 'Reconocimiento de señales',           valor: 'Sí' },
      { label: 'Asistencia activa de manejo',         valor: 'Sí' },
      { label: 'Visión 360°',                         valor: 'Sí' },
      { label: 'Punto ciego y ruta transversal',      valor: 'Sí' },
      { label: 'Clasificación de ocupantes',          valor: 'Sí' },
      { label: 'TPMS',                                valor: 'Sí' },
      { label: 'Sensores de estacionamiento',         valor: 'Delanteros y traseros con stop' },
      { label: 'Detección de fatiga',                 valor: 'Sí' },
      { label: 'Mantenimiento de carril',             valor: 'Sí' },
      { label: 'Autoestacionamiento',                 valor: 'Paralelo y perpendicular con stop' },
      { label: 'Colisión en intersecciones',          valor: 'Sí' },
      { label: 'Llanta de refacción',                 valor: 'Convencional' },
      { label: 'Freno de estacionamiento',            valor: 'Eléctrico' },
    ],
  },
]

// ── Jeep Renegade 2026 ───────────────────────────────────────────────────────

const RENEGADE_LATITUDE: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                    valor: '1.3 L Turbo' },
      { label: 'Potencia',                 valor: '173 hp @ 5,750 rpm' },
      { label: 'Torque',                   valor: '199 lb-pie @ 1,850 rpm' },
      { label: 'Arranque remoto',          valor: 'Sí' },
      { label: 'Tanque de combustible',    valor: '60 L gasolina' },
      { label: 'Transmisión',              valor: 'Automática 6 velocidades' },
      { label: 'Paletas al volante',       valor: 'No incluidas' },
      { label: 'Tracción',                 valor: 'Delantera (FWD)' },
      { label: 'Dirección',                valor: 'Eléctrica' },
      { label: 'Diámetro de giro',         valor: '10.84 m' },
      { label: 'Suspensión delantera',     valor: 'McPherson, brazos oscilantes + barra estabilizadora' },
      { label: 'Suspensión trasera',       valor: 'McPherson + barra estabilizadora' },
      { label: 'Salida 12V',               valor: 'Sí' },
      { label: 'Peso vehicular',           valor: '1,453 kg' },
      { label: 'Peso bruto',               valor: '1,853 kg' },
      { label: 'Capacidad de carga',       valor: '400 kg' },
      { label: 'Capacidad de arrastre',    valor: '400 kg' },
      { label: 'Maletero',                 valor: '314 L | 1,381 L con asiento abatido' },
      { label: 'Ángulos off-road',         valor: 'Entrada 22° | ventral 31° | salida 22°' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',                       valor: 'Piel' },
      { label: 'Asientos traseros',               valor: '60/40' },
      { label: 'Asiento conductor',               valor: 'Manual 6 vías' },
      { label: 'Asiento pasajero',                valor: 'Manual 4 vías' },
      { label: 'Cielo interior',                  valor: '—' },
      { label: 'Quemacocos',                      valor: 'No incluido' },
      { label: 'Pantalla táctil',                 valor: '8.4"' },
      { label: 'Audio',                           valor: '6 altavoces' },
      { label: 'Carga inalámbrica',               valor: 'Sí' },
      { label: 'USB remoto',                      valor: 'Sí' },
      { label: 'USB central',                     valor: 'Tipo A y Tipo C' },
      { label: 'Volante',                         valor: 'Tecnopiel' },
      { label: 'Columna de dirección',            valor: 'Ajuste de altura y profundidad' },
      { label: 'Controles de audio al volante',   valor: 'Sí' },
      { label: 'Control de teléfono al volante',  valor: 'Con reconocimiento de voz' },
      { label: 'Cristales eléctricos',            valor: 'Sí' },
      { label: 'Descansabrazos frontal',          valor: 'Deslizable con compartimiento de almacenamiento' },
      { label: 'Portavasos frontal',              valor: 'Iluminado' },
      { label: 'A/C',                             valor: 'Automático doble zona' },
      { label: 'Cubierta maletero',               valor: 'Desmontable' },
      { label: 'Ganchos maletero',                valor: 'Sí' },
      { label: 'Tapetes',                         valor: 'Frontales y traseros Jeep®' },
      { label: 'Clúster',                         valor: 'TFT 7" a color' },
      { label: 'Guantera',                        valor: 'Con iluminación' },
      { label: 'Espejo retrovisor',               valor: 'Día/noche manual' },
      { label: 'Desempañante trasero',            valor: 'Sí' },
      { label: 'Parasol',                         valor: 'Con espejo de vanidad e iluminación' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Iluminación frontal',         valor: 'LED' },
      { label: 'Lámparas traseras',           valor: 'LED' },
      { label: 'Faros de niebla',             valor: 'Sí' },
      { label: 'Luces diurnas (DRL)',         valor: 'Sí' },
      { label: 'Espejos laterales',           valor: 'Eléctricos, plegables manualmente, con indicador direccional' },
      { label: 'Cambio luces inteligente',    valor: 'No incluido' },
      { label: 'Neumáticos',                  valor: '225/55R18' },
      { label: 'Rines',                       valor: 'Aluminio 18"' },
      { label: 'Rieles laterales en techo',   valor: 'Sí' },
      { label: 'Manijas',                     valor: 'Al color de la carrocería' },
      { label: 'Techo bitono',                valor: 'No incluido' },
      { label: 'Longitud',                    valor: '4,268 mm' },
      { label: 'Ancho',                       valor: '1,805 mm' },
      { label: 'Altura',                      valor: '1,692 mm' },
      { label: 'Distancia entre ejes',        valor: '2,570 mm' },
      { label: 'Colores disponibles',         valor: 'Negro Carbón, Gris Granito, Gris Mantarraya' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',                       valor: 'Disco en 4 ruedas' },
      { label: 'Freno de estacionamiento',         valor: 'Eléctrico' },
      { label: 'Control de estabilidad (ESC)',     valor: 'Sí' },
      { label: 'Arranque en pendiente (HSA)',      valor: 'Sí' },
      { label: 'Control de tracción',              valor: 'TC' },
      { label: 'Asistencia freno de pánico',       valor: 'Sí' },
      { label: 'Control crucero',                  valor: 'Sí' },
      { label: 'Limitación de velocidad',          valor: 'Sí' },
      { label: 'Llave tipo control',               valor: 'Sí' },
      { label: 'Acceso pasivo',                    valor: 'Sí' },
      { label: 'Cierre centralizado',              valor: 'Sí' },
      { label: 'Cinturones traseros',              valor: '3 puntos con limitador de carga' },
      { label: 'Cámara de reversa',                valor: 'Sí' },
      { label: 'Sensores estacionamiento',         valor: 'Sí' },
      { label: 'Bolsa frontal',                    valor: 'Conductor y pasajero' },
      { label: 'Bolsas laterales delanteras',      valor: 'Sí' },
      { label: 'Bolsa cortina',                    valor: 'Sí' },
      { label: 'Bolsa rodillas conductor',         valor: 'No incluida' },
      { label: 'ISOFIX',                           valor: 'Sí' },
      { label: 'TPMS',                             valor: 'Sí' },
      { label: 'Asistencia balanceo de remolque',  valor: 'Sí' },
      { label: 'Alerta cinturón trasero',          valor: 'Sí' },
      { label: 'Alarma',                           valor: 'Sí' },
      { label: 'Llanta de refacción',              valor: 'Convencional' },
      { label: 'Detección de fatiga',              valor: 'No incluida' },
      { label: 'Cambio de carril',                 valor: 'No incluido' },
      { label: 'Conducción en carril',             valor: 'No incluido' },
      { label: 'Colisión frontal plus',            valor: 'No incluida' },
      { label: 'Reconocimiento de señales',        valor: 'No incluido' },
      { label: 'Monitor de punto ciego',           valor: 'No incluido' },
      { label: 'Autoestacionamiento',              valor: 'No incluido' },
      { label: 'Sensor de lluvia',                 valor: 'No incluido' },
    ],
  },
]

const RENEGADE_LIMITED_S: Categoria[] = merge(RENEGADE_LATITUDE, {
  desempeno: {
    'Paletas al volante': 'Sí',
    'Peso vehicular':     '1,495 kg',
    'Peso bruto':         '1,895 kg',
    'Ángulos off-road':   'Entrada 21° | ventral 30° | salida 21°',
  },
  interior: {
    'Cielo interior':    'Negro',
    'Quemacocos':        'Eléctrico',
    'Espejo retrovisor': 'Electrocrómico',
  },
  exterior: {
    'Iluminación frontal':      'LED automáticas',
    'Cambio luces inteligente': 'SmartBeam',
    'Neumáticos':               '235/45R19',
    'Rines':                    'Aluminio 19"',
    'Techo bitono':             'Black (exterior bitono)',
    'Colores disponibles':      'Gris Granito, Gris Mantarraya, Blanco Polar',
  },
  seguridad: {
    'Control de tracción':       'TC+',
    'Detección de fatiga':       'Sí',
    'Cambio de carril':          'Sí',
    'Conducción en carril':      'Sí',
    'Colisión frontal plus':     'Sí',
    'Reconocimiento de señales': 'Sí',
    'Monitor de punto ciego':    'Sí',
    'Autoestacionamiento':       'Paralelo y perpendicular',
    'Sensor de lluvia':          'Sí',
    'Bolsa rodillas conductor':  'Sí',
  },
})

export const MODELOS_JEEP: ModeloFicha[] = [
  {
    id: 'grand-cherokee-2026',
    marca: 'Jeep',
    modelo: 'Grand Cherokee',
    año: 2026,
    versiones: [
      { id: 'altitude-4x2',   nombre: 'Altitude 4X2',    categorias: GC_BASE },
      { id: 'limited-4x4',    nombre: 'Limited 4X4',     categorias: GC_LIMITED },
      { id: 'limited-l-4x4',  nombre: 'Limited L 4X4',   categorias: GC_LIMITED_L },
      { id: 'summit-4x4',     nombre: 'Summit 4X4',      categorias: GC_SUMMIT },
    ],
  },
  {
    id: 'commander-2026',
    marca: 'Jeep',
    modelo: 'Commander',
    año: 2026,
    versiones: [
      { id: 'overland-2026', nombre: 'Overland', categorias: COMMANDER_BASE_CATS('2026') },
    ],
  },
  {
    id: 'jeep-compass-2026', marca: 'Jeep', modelo: 'Compass', año: 2026,
    versiones: [
      { id: 'limited-premium', nombre: 'Limited Premium', categorias: COMPASS_2026_LIMITED_PREMIUM },
      { id: 'altitude',        nombre: 'Altitude',        categorias: COMPASS_2026_ALTITUDE        },
      { id: 'high-altitude',   nombre: 'High Altitude',   categorias: COMPASS_2026_HIGH_ALTITUDE   },
    ],
  },
  {
    id: 'cherokee-hibrido-2026',
    marca: 'Jeep',
    modelo: 'Cherokee Híbrido',
    año: 2026,
    versiones: [
      { id: 'limited-4x4',  nombre: 'Limited 4X4',  categorias: CHEROKEE_HIBRIDO_LIMITED  },
      { id: 'overland-4x4', nombre: 'Overland 4X4', categorias: CHEROKEE_HIBRIDO_OVERLAND },
    ],
  },
  {
    id: 'grand-wagoneer-l-2026',
    marca: 'Jeep',
    modelo: 'Grand Wagoneer L',
    año: 2026,
    versiones: [
      { id: 'limited-4x4', nombre: 'Limited 4X4', categorias: GRAND_WAGONEER_L_LIMITED },
    ],
  },
  {
    id: 'renegade-2026',
    marca: 'Jeep',
    modelo: 'Renegade',
    año: 2026,
    versiones: [
      { id: 'latitude',   nombre: 'Latitude',   categorias: RENEGADE_LATITUDE  },
      { id: 'limited-s',  nombre: 'Limited "S"', categorias: RENEGADE_LIMITED_S },
    ],
  },
]
