import { Categoria, ModeloFicha, merge } from './_shared'

// ─────────────────────────────────────────────────────────────────────────────
// JEEP GRAND CHEROKEE 2026
// ─────────────────────────────────────────────────────────────────────────────

const GC_BASE: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                        valor: 'Hurricane Turbo W/ESS' },
      { label: 'Potencia',                     valor: '324 hp' },
      { label: 'Torque',                       valor: '332 lb-pie' },
      { label: 'Transmisión',                  valor: 'Automática 8 vel. 8HP80' },
      { label: 'Tracción',                     valor: '4X2 (FWD)' },
      { label: 'Sistema Selec-Terrain®',       valor: 'No incluido' },
      { label: 'Suspensión delantera',         valor: 'Independiente' },
      { label: 'Suspensión trasera',           valor: 'Independiente multilink' },
      { label: 'Suspensión neumática',         valor: 'No incluida' },
      { label: 'Diferencial frontal',          valor: 'No aplica (4X2)' },
      { label: 'Diferencial trasero (LSD)',    valor: 'No incluido' },
      { label: 'Receptor de remolque',         valor: 'No incluido' },
      { label: 'Dirección',                    valor: 'Eléctrica' },
      { label: 'Diámetro de giro',             valor: '11.3 m' },
      { label: 'Peso bruto vehicular',         valor: '2,744 kg' },
      { label: 'Capacidad de carga',           valor: '476 kg' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Pasajeros',                     valor: '5' },
      { label: 'Filas de asientos',             valor: '2' },
      { label: 'Tapicería',                     valor: 'Leatherette y gamuza' },
      { label: 'Techo interior',                valor: 'Negro' },
      { label: 'Asientos delanteros calef.',    valor: 'Sí' },
      { label: 'Asientos delanteros ventilados',valor: 'No incluidos' },
      { label: 'Asientos delanteros con masaje',valor: 'No incluidos' },
      { label: 'Ajuste asiento conductor',      valor: 'Eléctrico 8 vías' },
      { label: 'Memoria asiento conductor',     valor: 'No incluida' },
      { label: 'Ajuste asiento pasajero',       valor: 'Manual 4 vías' },
      { label: 'Memoria asiento pasajero',      valor: 'No incluida' },
      { label: 'Segunda fila',                  valor: '60/40 plegable' },
      { label: 'Segunda fila calefactable',     valor: 'No incluida' },
      { label: 'Segunda fila ventilada',        valor: 'No incluida' },
      { label: 'Segunda fila cortinillas',      valor: 'No incluidas' },
      { label: 'Tercera fila',                  valor: 'No incluida' },
      { label: 'Pantalla principal',            valor: 'Uconnect® 5 — 12.3" táctil' },
      { label: 'Clúster',                       valor: '10.25" TFT a color' },
      { label: 'Head-Up Display',               valor: 'No incluido' },
      { label: 'Pantalla interactiva pasajero', valor: 'No incluida' },
      { label: 'Visualiz. de mapas en clúster', valor: 'No incluida' },
      { label: 'Audio',                         valor: '6 altavoces premium' },
      { label: 'Amplificador',                  valor: 'No especificado' },
      { label: 'Supresión activa de ruido',     valor: 'Sí' },
      { label: 'Apple CarPlay / Android Auto',  valor: 'Sí' },
      { label: 'Iluminación ambiental',         valor: 'No incluida' },
      { label: 'Iluminación cortesía puertas',  valor: 'No incluida' },
      { label: 'Puerto USB 2ª fila',            valor: 'Sí' },
      { label: 'Puerto USB 3ª fila',            valor: 'No aplica' },
      { label: 'Espejo retrovisor interior',    valor: 'Estándar' },
      { label: 'Columna dirección con memoria', valor: 'No incluida' },
      { label: 'Control apertura de garage',    valor: 'No incluido' },
      { label: 'Aire acondicionado',            valor: 'Automático doble zona' },
      { label: 'Volante',                       valor: 'Tecnopiel' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Neumáticos',            valor: '265/50R20 Performance A/S' },
      { label: 'Rines',                 valor: 'Aluminio 20×8.5 negro brillante' },
      { label: 'Quemacocos',            valor: 'Eléctrico' },
      { label: 'Techo panorámico',      valor: 'No incluido' },
      { label: 'Exterior bitono',       valor: 'No' },
      { label: 'Luces delanteras',      valor: 'LED automáticas' },
      { label: 'Faros de niebla',       valor: 'No incluidos' },
      { label: 'Luces traseras',        valor: 'LED' },
      { label: 'Espejos plegado',       valor: 'Manual' },
      { label: 'Espejos señalización',  valor: 'No incluida' },
      { label: 'Maletero',              valor: 'Apertura eléctrica' },
      { label: 'Rieles en techo',       valor: 'Negro brillante' },
      { label: 'Longitud',              valor: '4,915 mm' },
      { label: 'Ancho sin espejos',     valor: '1,969 mm' },
      { label: 'Altura',                valor: '1,798 mm' },
      { label: 'Distancia entre ejes',  valor: '2,964 mm' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS 4 ruedas',           valor: 'Sí' },
      { label: 'Control de estabilidad',         valor: 'Sí' },
      { label: 'Crucero adaptativo (ACC)',        valor: 'Con Stop & Go' },
      { label: 'Detección colisión frontal',     valor: 'Plus' },
      { label: 'Asistencia en intersección',     valor: 'Sí' },
      { label: 'Frenado peatones/ciclistas',     valor: 'Sí' },
      { label: 'Punto ciego y ruta transversal', valor: 'Sí' },
      { label: 'Visión envolvente 360°',         valor: 'No incluida' },
      { label: 'Advertencia distancia lateral',  valor: 'No incluida' },
      { label: 'Cámara Off-Road integrada',      valor: 'No incluida' },
      { label: 'Visión nocturna',                valor: 'No incluida' },
      { label: 'Asistencia de carril',           valor: 'Sí' },
      { label: 'Reconocimiento de señales',      valor: 'Sí' },
      { label: 'Control descenso en pendientes', valor: 'No incluido' },
      { label: 'Detección de fatiga',            valor: 'No incluida' },
      { label: 'Sensores de estacionamiento',    valor: 'Traseros con función stop' },
      { label: 'Autoestacionamiento',            valor: 'No incluido' },
      { label: 'Acceso pasivo (keyless)',         valor: 'Puertas frontales' },
      { label: 'Freno de estacionamiento',       valor: 'Eléctrico' },
      { label: 'Arranque en pendiente (HSA)',    valor: 'Sí' },
      { label: 'Bolsas de aire',                 valor: '8 (frontales + rodillas + laterales + cortina)' },
      { label: 'Monitor presión neumáticos',     valor: 'Sí' },
      { label: 'Alarma',                         valor: 'Sí' },
    ],
  },
]

const GC_LIMITED: Categoria[] = merge(GC_BASE, {
  desempeno: {
    'Tracción':                  'Quadra-Trac I® (4X4)',
    'Sistema Selec-Terrain®':    'Sí',
    'Diferencial frontal':       'Convencional con eje desconectable',
  },
  interior: {
    'Tapicería':                     'Piel Nappa',
    'Asientos delanteros ventilados':'Sí',
    'Ajuste asiento conductor':      'Eléctrico 8 vías',
    'Memoria asiento conductor':     'Sí',
    'Ajuste asiento pasajero':       'Eléctrico 8 vías',
    'Segunda fila calefactable':     'Sí',
    'Audio':                         '9 altavoces + subwoofer',
    'Amplificador':                  '506 W',
    'Iluminación ambiental':         'LED',
    'Espejo retrovisor interior':    'Electrocrómico digital',
    'Columna dirección con memoria': 'Sí',
    'Control apertura de garage':    'Sí',
  },
  exterior: {
    'Rines':                '20×8.5 negro (diseño Overland)',
    'Techo panorámico':     'Doble panel panorámico',
    'Faros de niebla':      'LED frontales',
    'Espejos señalización': 'Sí',
  },
  seguridad: {
    'Visión envolvente 360°':        'Sistema de visión envolvente 360°',
    'Advertencia distancia lateral': 'Sí',
    'Cámara Off-Road integrada':     'Sí',
    'Sensores de estacionamiento':   'Delanteros y traseros con función stop',
    'Acceso pasivo (keyless)':       '4 puertas y maletero',
  },
})

const GC_LIMITED_L: Categoria[] = merge(GC_LIMITED, {
  interior: {
    'Pasajeros':              '7',
    'Filas de asientos':      '3',
    'Tercera fila':           '50/50 plegable manualmente',
    'Puerto USB 3ª fila':     'Sí',
    'Head-Up Display':        'Sí',
    'Aire acondicionado':     'Automático 3 zonas',
  },
  seguridad: {
    'Visión nocturna': 'Con detección de peatones y animales',
  },
})

const GC_SUMMIT: Categoria[] = merge(GC_LIMITED_L, {
  desempeno: {
    'Tracción':                 'Quadra-Trac II® (4X4 tiempo completo)',
    'Diferencial trasero (LSD)':'Con limitador de deslizamiento',
    'Receptor de remolque':     'Clase IV (cableado 7 y 4 pines)',
    'Suspensión neumática':     'Quadra-Lift® neumática',
  },
  interior: {
    'Tapicería':                     'Piel Palermo',
    'Asientos delanteros con masaje':'Sí',
    'Ajuste asiento conductor':      'Eléctrico 12 vías',
    'Ajuste asiento pasajero':       'Eléctrico 12 vías',
    'Memoria asiento pasajero':      'Sí',
    'Segunda fila ventilada':        'Sí',
    'Segunda fila cortinillas':      'Manuales',
    'Audio':                         '19 altavoces premium',
    'Amplificador':                  '950 W',
    'Iluminación ambiental':         'LED multicolor',
    'Iluminación cortesía puertas':  'Sí',
    'Pantalla interactiva pasajero': 'Sí',
    'Visualiz. de mapas en clúster': 'Sí',
    'Aire acondicionado':            'Automático 4 zonas',
    'Volante':                       'Piel',
  },
  exterior: {
    'Neumáticos':      '275/45R21XL All Season',
    'Rines':           '21×9.0 maquinados',
    'Exterior bitono': 'Sí',
    'Espejos plegado': 'Eléctrico',
    'Maletero':        'Eléctrico con manos libres (pie)',
  },
  seguridad: {
    'Control descenso en pendientes': 'Sí',
    'Detección de fatiga':            'Sí',
    'Autoestacionamiento':            'Paralelo y perpendicular con función stop',
  },
})

// ─────────────────────────────────────────────────────────────────────────────
// JEEP COMMANDER OVERLAND  2025 / 2026
// ─────────────────────────────────────────────────────────────────────────────

const COMMANDER_BASE_CATS = (v: '2025' | '2026'): Categoria[] => [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                  valor: v === '2025' ? 'Turbo 1.3L 4 cilindros con Start & Stop' : '1.3 L Turbo' },
      { label: 'Potencia',               valor: '173 hp @ 5,750 rpm' },
      { label: 'Torque',                 valor: '199 lb-ft @ 1,850 rpm' },
      { label: 'Transmisión',            valor: v === '2025' ? 'Automática 6 vel. AutoStick®' : 'Automática 6 vel. Aisin Gen3 + paletas' },
      { label: 'Tracción',               valor: 'FWD' },
      { label: 'Suspensión',             valor: 'McPherson delantera y trasera' },
      { label: 'Capacidad de carga',     valor: v === '2025' ? '400 kg' : '540 kg' },
      { label: 'Capacidad de arrastre',  valor: '400 kg' },
      { label: 'Peso bruto vehicular',   valor: '2,255 kg' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',               valor: v === '2025' ? 'Piel Nappa Premium y gamuza café' : 'Piel Brown Commander' },
      { label: 'Pasajeros',               valor: '7' },
      { label: 'Asientos delanteros',     valor: v === '2025' ? 'Eléctricos 8 vías' : 'Eléctricos 8 vías con memoria' },
      { label: 'Pantalla principal',      valor: v === '2025' ? 'Uconnect® 10.1" + Clúster 10.25"' : 'Infoentretenimiento 10.1"' },
      { label: 'Audio',                   valor: v === '2025' ? 'Harman Kardon® 9 bocinas + Subwoofer' : 'Sistema de audio premium' },
      { label: 'Carga inalámbrica',       valor: 'Sí' },
      { label: 'Quemacocos',              valor: v === '2025' ? 'Dual panorámico CommandView®' : 'Eléctrico' },
      { label: 'Apple CarPlay / Android Auto', valor: v === '2025' ? 'Inalámbrico' : 'No especificado' },
      { label: 'Aire acondicionado',      valor: v === '2025' ? 'Automático bizona' : 'Sistema de A/C' },
      { label: 'Cajuela',                 valor: v === '2025' ? '661 L + hasta 1,760 L (filas abatidas)' : '661 L' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Rines',                valor: v === '2025' ? 'Aluminio 19" Pirelli 235/50 R19' : 'Overland 19" — 235/50 R19' },
      { label: 'Techo',                valor: 'Bitono negro' },
      { label: 'Maletero',             valor: v === '2025' ? 'Eléctrico con manos libres (pie)' : 'Eléctrico con manos libres' },
      { label: 'Luces delanteras',     valor: 'LED automáticas' },
      { label: 'Luces traseras',       valor: 'LED' },
      { label: 'Faros de niebla',      valor: 'LED' },
      { label: 'Longitud',             valor: '4,769 mm' },
      { label: 'Ancho sin espejos',    valor: '1,859 mm' },
      { label: 'Altura',               valor: '1,685 mm' },
      { label: 'Distancia entre ejes', valor: '2,794 mm' },
      { label: 'Colores exteriores',   valor: v === '2025' ? 'Negro carbón, Plata martillado, Blanco polar, Gris granito, Slash gold' : 'Negro, Plata metálico, Granito cristal, Slash gold' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',                    valor: 'Sí' },
      { label: 'Control de estabilidad',         valor: v === '2025' ? 'ESC' : 'VDC' },
      { label: 'Crucero adaptativo (ACC)',        valor: v === '2025' ? 'Con Stop & Go' : 'Sí' },
      { label: 'Punto ciego',                    valor: v === '2025' ? 'BSCPD (con ruta transversal de reversa)' : 'Monitoreo de punto ciego' },
      { label: 'Visión 360°',                    valor: v === '2025' ? 'No incluida' : 'Sistema de visión 360°' },
      { label: 'Asistencia de carril',           valor: v === '2025' ? 'Lane Departure Plus' : 'Asistencia de mantenimiento y cambio de carril' },
      { label: 'Reconocimiento de señales',      valor: v === '2025' ? 'Sí' : 'Sí' },
      { label: 'Detección colisión frontal',     valor: v === '2025' ? 'Plus (con peatones y ciclistas)' : 'Plus FWD' },
      { label: 'Control tracción All Speed',     valor: v === '2025' ? 'Sí' : 'Sí + TC+' },
      { label: 'Freno Hill Holder',              valor: v === '2025' ? 'HSA' : 'Hill Holder + Auto Hold' },
      { label: 'Limitador de velocidad activo',  valor: v === '2025' ? 'No especificado' : 'Sí' },
      { label: 'ISOFIX',                         valor: 'Sí' },
      { label: 'Autoestacionamiento',            valor: 'Paralelo y perpendicular' },
      { label: 'Monitor presión neumáticos',     valor: 'Sí' },
    ],
  },
]

// ── Jeep Compass 2026 ────────────────────────────────────────────────────────

const COMPASS_2026_LIMITED_PREMIUM: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                 valor: '1.3 L Turbo' },
      { label: 'Potencia',              valor: '173 hp @5,750 rpm' },
      { label: 'Torque',                valor: '199 lb-pie @1,850 rpm' },
      { label: 'Tanque de combustible', valor: '60 L gasolina' },
      { label: 'Tecnología',            valor: 'Start & Stop – ESS' },
      { label: 'Arranque remoto',       valor: 'Sí' },
      { label: 'Transmisión',           valor: 'Automática 6 velocidades' },
      { label: 'Tracción',              valor: 'Delantera FWD' },
      { label: 'Caja de transferencia', valor: 'No aplica (FWD)' },
      { label: 'Sistema Selec Terrain', valor: 'No incluido' },
      { label: 'Paletas al volante',    valor: 'Sí' },
      { label: 'Columna de dirección',  valor: 'Ajustable' },
      { label: 'Dirección',             valor: 'Eléctrica' },
      { label: 'Diámetro de giro',      valor: '11.3 m' },
      { label: 'Toma auxiliar',         valor: '12 V' },
      { label: 'Suspensión',            valor: 'McPherson, ruedas independientes + barra estabilizadora' },
      { label: 'Ángulos off-road',      valor: 'Entrada 21.5° | ventral 20.5° | salida 30.7°' },
      { label: 'Capacidad de carga',    valor: '400 kg' },
      { label: 'Capacidad de arrastre', valor: '400 kg' },
      { label: 'Maletero',              valor: '476 L | 1,180 L asiento abatido' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',              valor: 'Piel Black' },
      { label: 'Asiento conductor',      valor: 'Manual 6 vías' },
      { label: 'Ajuste lumbar conductor',valor: '—' },
      { label: 'Asiento pasajero',       valor: 'Manual 4 vías' },
      { label: 'Cristales',              valor: 'Eléctricos' },
      { label: 'Desempañante trasero',   valor: 'Sí' },
      { label: 'Pantalla táctil',        valor: '10.1"' },
      { label: 'Clúster',                valor: '—' },
      { label: 'Audio',                  valor: '6 altavoces – Beats' },
      { label: 'Carga inalámbrica',      valor: 'Sí' },
      { label: 'Conectividad',           valor: 'USB Tipo A-C' },
      { label: 'USB 2ª fila',            valor: 'Tipo A, C' },
      { label: 'Consola frontal',        valor: 'Sí' },
      { label: 'Descansabrazos frontal', valor: 'Sí' },
      { label: 'Descansabrazos trasero', valor: 'Sí' },
      { label: 'Volante',                valor: 'Forrado en piel' },
      { label: 'A/C',                    valor: 'Sí' },
      { label: 'Sistema purificación aire', valor: '—' },
      { label: 'Ventilas 2ª fila',       valor: '—' },
      { label: 'Cubierta maletero',      valor: 'Desmontable' },
      { label: 'Ganchos maletero',       valor: 'Sí' },
      { label: '2ª fila',                valor: '60/40 plegable' },
      { label: 'Reposacabezas traseros', valor: '3 pasajeros' },
      { label: 'Tapetes',                valor: 'Frontales/traseros' },
      { label: 'Espejo retrovisor',      valor: 'Día/noche manual' },
      { label: 'Iluminación lectura',    valor: 'Frontal/trasero' },
      { label: 'Iluminación ambiental',  valor: 'LED' },
      { label: 'Iluminación maletero',   valor: 'De cortesía' },
      { label: 'Quemacocos',             valor: 'Eléctrico' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Iluminación frontal',         valor: 'LED automática' },
      { label: 'Iluminación diurna LED',      valor: '—' },
      { label: 'Faros de niebla',             valor: 'LED' },
      { label: 'Entrada con cortesía',        valor: 'Sí' },
      { label: 'Espejos laterales',           valor: 'Abatibles manualmente, negro' },
      { label: 'Cambio de luces inteligente', valor: '—' },
      { label: 'Limpiador medallón',          valor: 'Sí' },
      { label: 'Manijas',                     valor: 'Al color de la carrocería' },
      { label: 'Barras de toldo',             valor: 'Black' },
      { label: 'Rines',                       valor: 'Aluminio 18"' },
      { label: 'Neumáticos',                  valor: '225/55R18' },
      { label: 'Techo',                       valor: 'Al color de la carrocería' },
      { label: 'Cristales con tinte profundo',valor: '—' },
      { label: 'Puerta de maletero',          valor: '—' },
      { label: 'Open & Go',                   valor: '—' },
      { label: 'Peso vehicular',              valor: '1,557 kg' },
      { label: 'Peso bruto',                  valor: '1,957 kg' },
      { label: 'Longitud',                    valor: '4,404 mm' },
      { label: 'Ancho',                       valor: '1,819 mm' },
      { label: 'Altura',                      valor: '1,625 mm' },
      { label: 'Distancia entre ejes',        valor: '2,636 mm' },
      { label: 'Colores disponibles',         valor: 'Negro Diamante, Blanco Polar, Gris Granito, Azul Jazz' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',                   valor: 'Disco frontal/trasero' },
      { label: 'Freno de estacionamiento',      valor: 'Eléctrico' },
      { label: 'Arranque en pendientes (HSA)',  valor: 'Sí' },
      { label: 'Control de tracción (TC+)',     valor: 'Sí' },
      { label: 'Cámara de reversa',             valor: 'Sí' },
      { label: 'Control dinámico (VDC)',        valor: 'Sí' },
      { label: 'Control crucero',               valor: 'Sí' },
      { label: 'Control de tracción All Speed', valor: 'Sí' },
      { label: 'Control anti vuelco',           valor: 'Sí' },
      { label: 'Asistencia balanceo remolque',  valor: 'Sí' },
      { label: 'Auto Hold',                     valor: 'Sí' },
      { label: 'Limitador de velocidad',        valor: 'Sí' },
      { label: 'Luces traseras adaptativas',    valor: 'Sí' },
      { label: 'Cierre centralizado',           valor: 'Sí' },
      { label: 'Cinturones traseros',           valor: 'Con retractor' },
      { label: 'Sensor de lluvia',              valor: 'Sí' },
      { label: 'Bolsas de aire frontal',        valor: 'Conductor/pasajero' },
      { label: 'Bolsas de aire laterales',      valor: 'Asiento' },
      { label: 'Bolsa de aire cortina',         valor: 'Sí' },
      { label: 'Bolsa rodillas conductor',      valor: '—' },
      { label: 'Asistencia estacionamiento',    valor: 'Paralelo y perpendicular' },
      { label: 'Sensores estacionamiento',      valor: 'Sí' },
      { label: 'TPMS',                          valor: 'Sí' },
      { label: 'Smart Key',                     valor: 'Sí' },
      { label: 'Acceso pasivo',                 valor: '—' },
      { label: 'Clasificación de ocupantes',    valor: 'Sí' },
      { label: 'ISOFIX',                        valor: 'Sí' },
      { label: 'Alerta cinturones',             valor: 'Delanteros/traseros' },
      { label: 'Refacción',                     valor: 'Tamaño convencional' },
      { label: 'Alarma',                        valor: 'Sí' },
      { label: 'Colisión frontal (Full Speed)',  valor: '—' },
      { label: 'Mantenimiento de carril',        valor: '—' },
      { label: 'Señales de tránsito',           valor: '—' },
      { label: 'Detección de fatiga',           valor: '—' },
      { label: 'Frenado emergencia peatón',     valor: '—' },
      { label: 'Monitor punto ciego',           valor: '—' },
    ],
  },
]

const COMPASS_2026_ALTITUDE: Categoria[] = merge(COMPASS_2026_LIMITED_PREMIUM, {
  desempeno: {
    'Ángulos off-road': 'Entrada 20.6° | ventral 20.1° | salida 30.8°',
  },
  interior: {
    'Asiento conductor': 'Eléctrico 8 vías',
    'Clúster':           'TFT 10.25"',
    'Espejo retrovisor': 'Electrocrómico',
  },
  exterior: {
    'Espejos laterales':           'Plegables eléctricamente, con memoria e iluminación de cortesía',
    'Cambio de luces inteligente': 'Sí',
    'Rines':                       'Aluminio 19"',
    'Neumáticos':                  '235/45R19',
    'Techo':                       'Negro – bitono',
    'Peso vehicular':              '1,566 kg',
    'Peso bruto':                  '1,966 kg',
  },
  seguridad: {
    'Control crucero':             'Adaptativo (ACC)',
    'Colisión frontal (Full Speed)':'Sí',
    'Mantenimiento de carril':     'Sí',
    'Señales de tránsito':         'Sí',
    'Detección de fatiga':         'Sí',
    'Frenado emergencia peatón':   'Sí',
    'Monitor punto ciego':         'Sí',
  },
})

const COMPASS_2026_HIGH_ALTITUDE: Categoria[] = merge(COMPASS_2026_ALTITUDE, {
  desempeno: {
    'Motor':                  '2.0L I4 DOHC DI Turbo',
    'Potencia':                '200 hp @ 5,000 rpm',
    'Torque':                  '221 lb-pie @ 1,750 rpm',
    'Transmisión':             'Automática 8 velocidades 8F30',
    'Tracción':                'AWD',
    'Diámetro de giro':        '15.7 m',
    'Suspensión':              'Delantera McPherson; trasera Chapman con eslabones de acero, resortes helicoidales + barra estabilizadora',
    'Ángulos off-road':        'Entrada 16.1° | ventral 22.6° | salida 31.4°',
    'Capacidad de carga':      '466 kg',
    'Capacidad de arrastre':   '908 kg',
    'Caja de transferencia':   'Active Drive Full Time 4x4',
    'Sistema Selec Terrain':   'Sí',
  },
  interior: {
    'Tapicería':                  'Piel',
    'Asiento pasajero':           'Manual 6 vías',
    'Pantalla táctil':            '10.1" Uconnect 5 con GPS',
    'A/C':                        'Automático doble zona',
    'Audio':                      'Premium Alpine',
    'Consola frontal':            'Deslizable con descansabrazos',
    'Descansabrazos trasero':     'Con porta vasos',
    'Quemacocos':                 'Techo panorámico',
    'Ajuste lumbar conductor':    'Eléctrico 2 vías',
    'Sistema purificación aire':  'Sí (Jeep®)',
    'Ventilas 2ª fila':           'Sí',
  },
  exterior: {
    'Espejos laterales':            'Plegables manualmente, ajuste eléctrico, calefactables, con indicadores',
    'Peso vehicular':               '1,711 kg',
    'Peso bruto':                   '2,177 kg',
    'Ancho':                        '1,874 mm',
    'Altura':                       '1,647 mm',
    'Colores disponibles':          'Plata Metálico, Negro Diamante, Blanco Brillante',
    'Iluminación diurna LED':       'Sí',
    'Cristales con tinte profundo': 'Sí',
    'Puerta de maletero':           'Eléctrica con activación con pie',
    'Open & Go':                    'Sí',
  },
  seguridad: {
    'Bolsa rodillas conductor': 'Sí',
    'Acceso pasivo':            'Puertas frontales',
  },
})

export const MODELOS_JEEP: ModeloFicha[] = [
  {
    id: 'grand-cherokee-2026',
    marca: 'Jeep',
    modelo: 'Grand Cherokee',
    año: 2026,
    versiones: [
      { id: 'altitude-4x2',   nombre: 'Altitude 4X2',    categorias: GC_BASE },
      { id: 'limited-4x4',    nombre: 'Limited 4X4',     categorias: GC_LIMITED },
      { id: 'limited-l-4x4',  nombre: 'Limited L 4X4',   categorias: GC_LIMITED_L },
      { id: 'summit-4x4',     nombre: 'Summit 4X4',      categorias: GC_SUMMIT },
    ],
  },
  {
    id: 'commander-2026',
    marca: 'Jeep',
    modelo: 'Commander',
    año: 2026,
    versiones: [
      { id: 'overland-2026', nombre: 'Overland', categorias: COMMANDER_BASE_CATS('2026') },
    ],
  },
  {
    id: 'jeep-compass-2026', marca: 'Jeep', modelo: 'Compass', año: 2026,
    versiones: [
      { id: 'limited-premium', nombre: 'Limited Premium', categorias: COMPASS_2026_LIMITED_PREMIUM },
      { id: 'altitude',        nombre: 'Altitude',        categorias: COMPASS_2026_ALTITUDE        },
      { id: 'high-altitude',   nombre: 'High Altitude',   categorias: COMPASS_2026_HIGH_ALTITUDE   },
    ],
  },
]
