import { Categoria, ModeloFicha, merge } from './_shared'

// ─────────────────────────────────────────────────────────────────────────────
// RAM 4000 2026  —  Reg Cab Chassis P / PL / Crew Cab Chassis
// ─────────────────────────────────────────────────────────────────────────────

const RAM_4000_REG_CAB_P: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                valor: '6.4L V8 HEMI Upgrade HD' },
      { label: 'Potencia',             valor: '405 HP @ 5,500 rpm' },
      { label: 'Torque',               valor: '429 lb-ft @ 4,000 rpm' },
      { label: 'Transmisión',          valor: 'Automática 8 velocidades' },
      { label: 'Tracción',             valor: 'Trasera' },
      { label: 'Selector tracción',    valor: 'No incluido' },
      { label: 'Dirección',            valor: 'Asistida' },
      { label: 'Suspensión delantera', valor: '3 links, barra transversal, resortes helicoidales, eje sólido y barra estabilizadora' },
      { label: 'Suspensión trasera',   valor: 'Muelles 2 etapas, eje sólido doble rodada, diferencial deslizamiento limitado, barra estabilizadora' },
      { label: 'Amortiguadores',       valor: 'Trabajo pesado' },
    ],
  },
  {
    id: 'dimensiones', nombre: 'Dimensiones y Capacidades', specs: [
      { label: 'Largo',                   valor: '5,977 mm' },
      { label: 'Ancho sin espejos',       valor: '2,118 mm' },
      { label: 'Alto',                    valor: '2,055 mm' },
      { label: 'Distancia entre ejes',    valor: '3,647 mm' },
      { label: 'Peso vehicular',          valor: '2,817 kg' },
      { label: 'Peso bruto vehicular',    valor: '—' },
      { label: 'Capacidad de carga',      valor: '3,305 kg' },
      { label: 'Capacidad de arrastre',   valor: '7,094 kg' },
      { label: 'Carga por ejes del/tra',  valor: '2,494 / 4,467 kg' },
      { label: 'Neumáticos',             valor: 'LT235/80R17E All Season' },
      { label: 'Rines',                   valor: 'Acero 17" negro' },
      { label: 'Llanta de refacción',     valor: 'Tamaño completo' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'A/C',                     valor: 'Sí, con filtro de cabina N95+BIO' },
      { label: 'Asiento conductor',       valor: 'Manual 4 posiciones' },
      { label: 'Asiento pasajero',        valor: 'Manual 4 posiciones' },
      { label: 'Asientos',                valor: 'Banco 40/20/40 en tela' },
      { label: 'Almacenamiento trasero',  valor: 'Detrás del asiento' },
      { label: 'Reposabrazos delantero',  valor: 'Con portavasos' },
      { label: 'Cabeceras delanteras',    valor: 'Ajuste 4 posiciones' },
      { label: 'Cabeceras traseras',      valor: 'No incluidas' },
      { label: 'Asiento trasero',         valor: 'No plegable' },
      { label: 'Bandeja de almacenamiento', valor: 'No incluida' },
      { label: 'Botón de arranque',       valor: 'Sí' },
      { label: 'Entrada remota sin llave', valor: 'No incluida' },
      { label: 'Cerraduras eléctricas',   valor: 'No incluidas' },
      { label: 'Consola superior',        valor: 'No incluida' },
      { label: 'Espejo retrovisor',       valor: 'Día/noche' },
      { label: 'Indicador temp. y brújula', valor: 'Sí' },
      { label: 'Piso',                    valor: 'Vinilo negro uso rudo' },
      { label: 'Palanca de cambios',      valor: 'Uretano en columna de dirección' },
      { label: 'Sistema antirrobo',       valor: 'Llave Sentry' },
      { label: 'Seguros de puertas',      valor: 'Manuales' },
      { label: 'Ventanas delanteras',     valor: 'Manuales' },
      { label: 'Ventanilla trasera',      valor: 'Fija' },
      { label: 'Pantalla',                valor: 'Táctil 8.4"' },
      { label: 'Clúster',                 valor: 'TFT color 3.5"' },
      { label: 'Apple CarPlay / Android Auto', valor: 'Sí' },
      { label: 'Audio',                   valor: '4 altavoces' },
      { label: 'Media Hub',               valor: '2 USB + auxiliar + carga y datos' },
      { label: 'Manos libres',            valor: 'Inalámbrico (teléfono y audio)' },
      { label: 'GPS',                     valor: 'Entrada de antena' },
      { label: 'Puerto USB carga remoto', valor: 'Sí' },
      { label: 'Toma 12V',               valor: 'Sí' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Faros',                   valor: 'LED automáticos con conducción diurna' },
      { label: 'Faros antiniebla',        valor: 'LED' },
      { label: 'Luces en toldo',          valor: 'Navegación' },
      { label: 'Espejos exteriores',      valor: 'Telescópicos ajuste manual, negro' },
      { label: 'Manijas de puerta',       valor: 'Negro' },
      { label: 'Parrilla',                valor: 'Malla negra mate' },
      { label: 'Ganchos de remolque',     valor: 'Sí' },
      { label: 'Arnés de remolque',       valor: '7 pines' },
      { label: 'Interruptores auxiliares', valor: 'Montados en consola central' },
      { label: 'Retardo apagado faros',   valor: 'Sí' },
      { label: 'Monitoreo voltaje ralentí', valor: 'Sí' },
      { label: 'Color exterior',          valor: 'Blanco brillante' },
      { label: 'Color interior',          valor: 'Negro' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',              valor: 'Disco en 4 ruedas' },
      { label: 'ESP (estabilidad)',        valor: 'Sí' },
      { label: 'Bolsas de aire',          valor: 'Delanteras multietapas' },
      { label: 'Colisión frontal',        valor: 'Sistema de asistencia plus' },
      { label: 'Frenado urgencia (peat./cicl.)', valor: 'Sí' },
      { label: 'Control crucero',         valor: 'Adaptativo con stop' },
      { label: 'Asistencia frenado',      valor: 'Ready Alert' },
      { label: 'Cinturones delanteros',   valor: 'Con ajuste de altura' },
      { label: 'Limpiaparabrisas',        valor: 'Intermitente' },
      { label: 'Aviso lámpara fundida LED', valor: 'Sí' },
      { label: 'Drive by Wire',           valor: 'Sí (acelerador electrónico)' },
      { label: 'Enfriador aceite trans.', valor: 'Auxiliar' },
      { label: 'Enfriamiento motor',      valor: 'Para trabajo pesado' },
    ],
  },
]

const RAM_4000_REG_CAB_PL: Categoria[] = merge(RAM_4000_REG_CAB_P, {
  desempeno: {
    'Transmisión': 'Automática 8 velocidades LCV',
  },
  dimensiones: {
    'Largo':                 '6,586 mm',
    'Ancho sin espejos':     '2,334 mm',
    'Alto':                  '2,029 mm',
    'Distancia entre ejes':  '4,249 mm',
    'Peso vehicular':        '2,843 kg',
    'Peso bruto vehicular':  '6,122 kg',
    'Capacidad de carga':    '3,279 kg',
    'Capacidad de arrastre': '7,067 kg',
  },
})

const RAM_4000_CREW_CAB: Categoria[] = merge(RAM_4000_REG_CAB_P, {
  desempeno: {
    'Transmisión':        'Automática 8 velocidades LCV',
    'Tracción':           '4x4',
    'Selector tracción':  'Electrónico en movimiento',
  },
  dimensiones: {
    'Largo':                '6,711 mm',
    'Alto':                 '2,047 mm',
    'Distancia entre ejes': '4,374 mm',
    'Peso vehicular':       '3,245 kg',
    'Capacidad de carga':   '2,877 kg',
    'Capacidad de arrastre':'6,663 kg',
  },
  interior: {
    'Almacenamiento trasero':   'Compartimento debajo del asiento trasero',
    'Reposabrazos delantero':   'No incluido',
    'Cabeceras traseras':       'Ajuste 2 posiciones',
    'Asiento trasero':          'Plegable',
    'Bandeja de almacenamiento':'Sí',
    'Entrada remota sin llave': 'Sí',
    'Cerraduras eléctricas':    'Sensibles a la velocidad',
    'Consola superior':         'Sí',
    'Seguros de puertas':       'Eléctricos',
    'Ventanas delanteras':      'Eléctricas un toque arriba y abajo',
    'Ventanilla trasera':       'Manual (trasera)',
    'Audio':                    '6 altavoces',
  },
})

// ─────────────────────────────────────────────────────────────────────────────
// RAM 1500 2026  —  Tungsten / Tradesman I6 4x4
// ─────────────────────────────────────────────────────────────────────────────

const RAM_1500_TUNGSTEN: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                valor: '3.0L I6 Hurricane HO Twin Turbo ESS' },
      { label: 'Potencia',             valor: '540 HP @ 6,200 rpm' },
      { label: 'Torque',               valor: '521 lb-ft @ 3,500 rpm' },
      { label: 'Transmisión',          valor: 'Automática 8 velocidades' },
      { label: 'Tracción',             valor: '4x4 (4WD)' },
      { label: 'Caja de transferencia', valor: 'Electrónica' },
      { label: 'Dirección',            valor: 'Eléctrica asistida' },
      { label: 'Modos de conducción',  valor: 'Configurables' },
      { label: 'Suspensión delantera', valor: 'Independiente brazos cortos/largos, Quadra-Lift® neumática semiactiva, barra estabilizadora' },
      { label: 'Suspensión trasera',   valor: 'Independiente 5 enlaces, resortes helicoidales, Quadra-Lift® neumática semiactiva, enlaces aluminio fundido' },
      { label: 'Arranque remoto',       valor: 'Sí' },
      { label: 'Sistema motor',        valor: '—' },
      { label: 'Alternador',           valor: '—' },
      { label: 'Relación eje trasero', valor: '—' },
      { label: 'Consumo ciudad',       valor: '—' },
      { label: 'Consumo carretera',    valor: '—' },
      { label: 'Consumo combinado',    valor: '—' },
      { label: 'Batería',              valor: '—' },
      { label: 'Inversor',             valor: '—' },
      { label: 'Tanque de combustible', valor: '—' },
    ],
  },
  {
    id: 'dimensiones', nombre: 'Dimensiones y Capacidades', specs: [
      { label: 'Largo',                  valor: '5,916 mm' },
      { label: 'Ancho',                  valor: '2,084 mm' },
      { label: 'Alto',                   valor: '1,971 mm' },
      { label: 'Distancia entre ejes',   valor: '—' },
      { label: 'Volumen de carga',       valor: '1.5 m³' },
      { label: 'Capacidad de carga',     valor: '530 kg' },
      { label: 'Capacidad de arrastre',  valor: '4,150 kg' },
      { label: 'Neumáticos',             valor: 'Pirelli All Season 285/45R22XL' },
      { label: 'Rines',                  valor: '22×9.0 pulido con insertos' },
      { label: 'Llanta de repuesto',     valor: 'Tamaño completo' },
    ],
  },
  {
    id: 'remolque', nombre: 'Remolque', specs: [
      { label: 'Enganche',               valor: 'Receptor clase IV' },
      { label: 'Arnés',                  valor: '7 pines + conector 12 vías/1 vía' },
      { label: 'Gancho del remolque',    valor: 'Sí' },
      { label: 'Control freno remolque', valor: 'Sí' },
      { label: 'Control dirección inversa', valor: 'Sí' },
      { label: 'Comprobación de luces',  valor: 'Sí' },
      { label: 'Monitor presión remolque', valor: 'Sí' },
      { label: 'Control balanceo',       valor: 'Sí' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',              valor: 'Piel premium envolvente' },
      { label: 'A/C',                    valor: 'Automático zona dual, filtro N95+BIO' },
      { label: 'Asiento conductor',      valor: 'Eléctrico 20 posiciones + lumbar 4 dirs + masaje + memoria' },
      { label: 'Asiento pasajero',       valor: 'Eléctrico 20 posiciones + lumbar 4 dirs + masaje' },
      { label: 'Asientos delanteros',    valor: 'Calefacción y ventilación' },
      { label: 'Asientos traseros',      valor: 'Calefacción, ventilación y reclinables 60/40' },
      { label: 'Cabeceras delanteras',   valor: 'Eléctricas 4 direcciones' },
      { label: 'Volante',                valor: 'Piel calefactable con insertos fibra de carbono real' },
      { label: 'Pedales',                valor: 'Ajuste eléctrico, acabado brillante' },
      { label: 'Memoria',                valor: 'Asiento conductor, espejos y pedales' },
      { label: 'Columna de dirección',   valor: 'Telescópica y con inclinación' },
      { label: 'Espejo retrovisor',      valor: 'Digital con modo remolque' },
      { label: 'Freno estacionamiento',  valor: 'Eléctrico' },
      { label: 'Cerraduras',             valor: 'Eléctricas sensibles a la velocidad' },
      { label: 'Keyless Entry & Go',     valor: 'Sí' },
      { label: 'Cristales delanteros',   valor: 'Eléctricos 1 toque arriba y abajo' },
      { label: 'Ventana trasera',        valor: 'Corrediza eléctrica' },
      { label: 'Vidrios',                valor: 'Tintados con protección solar' },
      { label: 'Iluminación ambiental',  valor: 'LED' },
      { label: 'Control activo ruido',   valor: 'Sí (cabina)' },
      { label: 'Control garaje universal', valor: 'Sí' },
      { label: 'Almacenamiento 2ª fila', valor: 'Sí (piso)' },
      { label: 'Acentos',               valor: '—' },
      { label: 'Perilla selectora',      valor: 'Sí' },
      { label: 'Tapetes',                valor: 'Sí' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Faros',                  valor: 'LED bifunción automáticos' },
      { label: 'Luces antiniebla',       valor: 'LED premium' },
      { label: 'DRL',                    valor: 'LED' },
      { label: 'Luces traseras',         valor: 'LED' },
      { label: 'Animación iluminación',  valor: 'Frontal y trasera exterior' },
      { label: 'Espejos exteriores',     valor: 'Eléctricos premium, cromados, calefactados, plegables automáticos, atenuación automática, luz direccional/cortesía, gran angular convexo, luz aproximación' },
      { label: 'Estribos',               valor: 'Plegables eléctricos' },
      { label: 'Altura de manejo',       valor: '—' },
      { label: 'Techo',                  valor: 'Corredizo panorámico doble panel' },
      { label: 'Performance Hood',       valor: '—' },
      { label: 'Escape',                 valor: 'Doble con puntas brillantes' },
      { label: 'Antena',                 valor: 'Aleta de tiburón' },
      { label: 'Manijas exteriores',     valor: 'Al color de la carrocería' },
      { label: 'Fascia delantera',       valor: 'Insertos en cromo; defensa trasera al color' },
      { label: 'Limpiaparabrisas',       valor: 'Sensibles a la lluvia' },
      { label: 'Portón trasero',         valor: 'Amortiguado con apertura remota + luz LED en manija' },
      { label: 'RAMBOX®',                valor: 'Sistema gestión de carga' },
      { label: 'Batea',                  valor: 'Protección aspersión + puerta multifunción + escalón desplegable + iluminación LED + 4 ganchos' },
      { label: 'Colores disponibles',    valor: 'Granite, Forger Blue, Molten Red, Bright White, Ivory White, Diamond Black' },
    ],
  },
  {
    id: 'tecnologia', nombre: 'Tecnología', specs: [
      { label: 'Pantalla principal',     valor: 'Táctil 14.4" — Apple CarPlay® y Android Auto' },
      { label: 'Clúster',                valor: 'TFT color 12"' },
      { label: 'Pantalla pasajero',      valor: '10.25"' },
      { label: 'Head-Up Display',        valor: 'Sí' },
      { label: 'Navegación GPS',         valor: 'Sí' },
      { label: 'Audio',                  valor: 'Klipsch® Premium — 23 bocinas' },
      { label: 'USB',                    valor: '2 con auxiliar + 2 con carga' },
      { label: 'Manos libres',           valor: 'Inalámbrico' },
      { label: 'Carga inalámbrica',      valor: '2 celulares simultáneos' },
      { label: 'Tomacorriente 12V',      valor: 'Sí' },
      { label: 'Tomacorriente 115V',     valor: 'Delantero y trasero' },
      { label: 'Info todoterreno',       valor: 'Páginas de información off-road' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',             valor: 'Disco en 4 ruedas' },
      { label: 'ESP + TCS',              valor: 'Sí' },
      { label: 'Control antivuelco',     valor: 'Sí' },
      { label: 'Bolsas de aire',         valor: 'Delanteras multietapas avanzadas + laterales delanteras + cortina trasera' },
      { label: 'ISOFIX',                 valor: 'Sí' },
      { label: 'Cámara',                 valor: 'Visión envolvente 360°' },
      { label: 'ParkSense®',             valor: 'Sensores delanteros y traseros con parada' },
      { label: 'Punto ciego y cruce',    valor: 'Detección activa' },
      { label: 'Control crucero',        valor: 'Adaptativo con Stop & Go' },
      { label: 'Control velocidad selectiva', valor: '—' },
      { label: 'Colisión frontal',       valor: 'Asistencia plus' },
      { label: 'Colisión intersecciones', valor: 'Asistencia activa' },
      { label: 'Frenado emergencia',     valor: 'Peatonal + avanzada' },
      { label: 'Asistencia carril',      valor: 'Salida activa' },
      { label: 'Dirección evasiva',      valor: 'Sí' },
      { label: 'Luz alta automática',    valor: 'Sí' },
      { label: 'Señales de tráfico',     valor: 'Reconocimiento automático' },
      { label: 'Conductor somnoliento',  valor: 'Detección activa' },
      { label: 'TPMS',                   valor: 'Sí' },
      { label: 'Arranque en subidas',    valor: 'Sí' },
      { label: 'Sistema activo conducción', valor: 'Sí' },
      { label: 'Amortiguadores',         valor: 'Delanteros y traseros uso rudo' },
      { label: 'Barra estabilizadora',   valor: 'Delantera y trasera' },
    ],
  },
]

const RAM_1500_TRADESMAN: Categoria[] = merge(RAM_1500_TUNGSTEN, {
  desempeno: {
    'Motor':               '3.0L I6 Hurricane SO Twin Turbo',
    'Potencia':            '420 HP @ 5,200 rpm',
    'Torque':              '469 lb-ft @ 3,500 rpm',
    'Modos de conducción': '—',
    'Suspensión delantera':'Horquillas independientes con resortes, amortiguador de gas y barra estabilizadora',
    'Suspensión trasera':  '5 links con resortes, eje sólido y barra estabilizadora',
    'Arranque remoto':     '—',
    'Sistema motor':       'Stop-Start con batería auxiliar',
    'Alternador':          '230A',
    'Relación eje trasero':'3.92',
    'Consumo ciudad':      '8.0 km/L',
    'Consumo carretera':   '12.0 km/L',
    'Consumo combinado':   '9.4 km/L',
    'Batería':             '700 amp, libre de mantenimiento',
    'Inversor':            '400W',
    'Tanque de combustible':'98 L',
  },
  dimensiones: {
    'Distancia entre ejes':  '3,672 mm',
    'Capacidad de carga':    '860 kg',
    'Capacidad de arrastre': '5,130 kg',
    'Neumáticos':            '275/65R18 BSW AS LRR',
    'Rines':                 'Acero 18"',
  },
  remolque: {
    'Arnés':                     '7 pines',
    'Gancho del remolque':       '—',
    'Control freno remolque':    'Control electrónico',
    'Control dirección inversa': '—',
    'Comprobación de luces':     '—',
    'Monitor presión remolque':  '—',
    'Control balanceo':          '—',
  },
  interior: {
    'Tapicería':              'Tela',
    'A/C':                    'Manual, filtro N95+BIO',
    'Asiento conductor':      'Manual 4 posiciones',
    'Asiento pasajero':       'Manual 4 posiciones',
    'Asientos delanteros':    '—',
    'Asientos traseros':      'Abatible',
    'Cabeceras delanteras':   'Ajustables 4 direcciones',
    'Volante':                '—',
    'Pedales':                '—',
    'Memoria':                '—',
    'Columna de dirección':   '—',
    'Espejo retrovisor':      'Día/noche',
    'Vidrios':                '—',
    'Iluminación ambiental':  '—',
    'Control activo ruido':   '—',
    'Control garaje universal':'—',
    'Tapetes':                'Delanteros y traseros',
  },
  exterior: {
    'Faros':               'LED reflector automático luces altas y bajas',
    'Luces antiniebla':    '—',
    'Luces traseras':      '—',
    'Animación iluminación':'—',
    'Espejos exteriores':  'Negros, ajuste eléctrico, inserto convexo',
    'Estribos':            'Escalón de caja plegable',
    'Techo':               '—',
    'Escape':              '—',
    'Manijas exteriores':  'Negro',
    'Fascia delantera':    'Negra (parrilla y manijas negras)',
    'Limpiaparabrisas':    '—',
    'Portón trasero':      'Con amortiguación',
    'RAMBOX®':             '—',
    'Batea':               'Recubrimiento aspersión + iluminación + 4 ganchos ajustables + toma 115V exterior',
    'Colores disponibles': 'Silver Zynith, Diamond Black, Bright White',
  },
  tecnologia: {
    'Pantalla principal':  'Táctil 8.4" — Apple CarPlay® y Android Auto',
    'Clúster':             'TFT color 3.5"',
    'Pantalla pasajero':   '—',
    'Head-Up Display':     '—',
    'Navegación GPS':      'Antena GPS',
    'Audio':               '6 altavoces',
    'USB':                 'Media Hub: 2 USB + auxiliar',
    'Carga inalámbrica':   '—',
    'Tomacorriente 115V':  '—',
    'Info todoterreno':    '—',
  },
  seguridad: {
    'Bolsas de aire':          '6 (frontales + laterales + cortina)',
    'Cámara':                  'Trasera',
    'Colisión intersecciones': '—',
    'Frenado emergencia':      'Peatonal',
    'Dirección evasiva':       '—',
    'Señales de tráfico':      '—',
    'Conductor somnoliento':   '—',
    'Sistema activo conducción':'—',
    'Amortiguadores':          'Trabajo pesado',
    'Barra estabilizadora':    '—',
  },
})

const RAM_1500_TRADESMAN_V6_4X2: Categoria[] = merge(RAM_1500_TUNGSTEN, {
  desempeno: {
    'Motor':               '3.6L V6 24V VVT eTorque Engine',
    'Potencia':            '305 HP @ 6,400 rpm',
    'Torque':              '269 lb-ft @ 4,800 rpm',
    'Tracción':            '4x2 (Trasera)',
    'Caja de transferencia':'No incluida',
    'Modos de conducción': '—',
    'Suspensión delantera':'Horquillas independientes con resortes, amortiguador de gas y barra estabilizadora',
    'Suspensión trasera':  '5 links con resortes, eje sólido y barra estabilizadora',
    'Arranque remoto':     '—',
    'Sistema motor':       'eTorque mild-hybrid 48V',
    'Alternador':          '—',
    'Relación eje trasero':'3.55',
    'Consumo ciudad':      '9.31 km/L',
    'Consumo carretera':   '13.3 km/L',
    'Consumo combinado':   '10.8 km/L',
    'Batería':             '730 amp, libre de mantenimiento',
    'Inversor':            '—',
    'Tanque de combustible':'98 L',
  },
  dimensiones: {
    'Distancia entre ejes':  '3,672 mm',
    'Capacidad de carga':    '912 kg',
    'Capacidad de arrastre': '3,370 kg',
    'Neumáticos':            '275/65R18 BSW AS LRR',
    'Rines':                 'Acero 18"',
    'Llanta de repuesto':    'Tamaño completo temporal',
  },
  remolque: {
    'Arnés':                     '7 pines',
    'Gancho del remolque':       '—',
    'Control freno remolque':    '—',
    'Control dirección inversa': '—',
    'Comprobación de luces':     '—',
    'Monitor presión remolque':  '—',
    'Control balanceo':          'Sí',
  },
  interior: {
    'Tapicería':              'Tela',
    'A/C':                    'Manual, filtro N95+BIO',
    'Asiento conductor':      'Manual 4 posiciones',
    'Asiento pasajero':       'Manual 4 posiciones',
    'Asientos delanteros':    '—',
    'Asientos traseros':      'Abatible 60/40',
    'Cabeceras delanteras':   'Ajustables 4 direcciones',
    'Volante':                '—',
    'Pedales':                '—',
    'Memoria':                '—',
    'Columna de dirección':   '—',
    'Espejo retrovisor':      'Día/noche',
    'Vidrios':                '—',
    'Iluminación ambiental':  '—',
    'Control activo ruido':   '—',
    'Control garaje universal':'—',
    'Tapetes':                'Delanteros y traseros',
  },
  exterior: {
    'Faros':               'LED reflector automático luces altas y bajas',
    'Luces antiniebla':    '—',
    'DRL':                 'En faro de baja intensidad',
    'Luces traseras':      '—',
    'Animación iluminación':'—',
    'Espejos exteriores':  'Negros, ajuste eléctrico, calefactables, inserto convexo',
    'Estribos':            '—',
    'Techo':               '—',
    'Escape':              'Doble en color negro',
    'Manijas exteriores':  'Negro',
    'Fascia delantera':    'Negra (parrilla y manijas negras)',
    'Limpiaparabrisas':    '—',
    'Portón trasero':      'Con amortiguación',
    'RAMBOX®':             '—',
    'Batea':               '—',
    'Colores disponibles': '—',
  },
  tecnologia: {
    'Pantalla principal':  'Táctil 8.4" — Apple CarPlay® y Android Auto',
    'Clúster':             'TFT color 3.5"',
    'Pantalla pasajero':   '—',
    'Head-Up Display':     '—',
    'Navegación GPS':      'Antena GPS',
    'Audio':               '6 altavoces',
    'USB':                 'Media Hub: 2 USB + auxiliar',
    'Carga inalámbrica':   '—',
    'Tomacorriente 115V':  '—',
    'Info todoterreno':    '—',
  },
  seguridad: {
    'Bolsas de aire':          '6 (frontales + laterales + cortina)',
    'Cámara':                  'Trasera',
    'Colisión intersecciones': '—',
    'Frenado emergencia':      'Peatonal',
    'Dirección evasiva':       '—',
    'Señales de tráfico':      '—',
    'Conductor somnoliento':   '—',
    'Sistema activo conducción':'—',
    'Amortiguadores':          'Trabajo pesado',
    'Barra estabilizadora':    '—',
  },
})

const RAM_1500_RHO: Categoria[] = merge(RAM_1500_TUNGSTEN, {
  desempeno: {
    'Transmisión':          'Automática 8 velocidades + paletas al volante',
    'Caja de transferencia':'Electrónica Full Time, Control Selec-Speed™',
    'Suspensión delantera': 'Horquillas independientes con resortes helicoidales, amortiguadores Bilstein e2 Black Hawk® Active Performance y barra estabilizadora',
    'Suspensión trasera':   '5 links con resortes helicoidales, amortiguadores Bilstein e2 Black Hawk® Active Performance, eje sólido y barra estabilizadora',
  },
  dimensiones: {
    'Capacidad de carga':    '690 kg',
    'Capacidad de arrastre': '3,800 kg',
    'Neumáticos':            'Goodyear All Terrain LT325/65R18D',
    'Rines':                 'Beadlock de aluminio 18×9.0"',
  },
  interior: {
    'Tapicería':            'Piel envolvente',
    'Pedales':              'Ajuste eléctrico',
    'Control activo ruido': '—',
    'Perilla selectora':    '—',
    'Acentos':              'Fibra de carbono real',
    'Tapetes':              'Mopar® delanteros y traseros',
  },
  exterior: {
    'Faros':              'Proyección LED con bifunción automática',
    'Luces antiniebla':   'LED',
    'Espejos exteriores': 'Negros, eléctricos premium, calefactados, plegables automáticos, atenuación automática, luz direccional/cortesía, gran angular convexo, luz aproximación',
    'Estribos':           'Off-road',
    'Performance Hood':   'Sí',
    'Escape':             'Doble con puntas en negro',
    'Manijas exteriores': 'Negro',
    'Fascia delantera':   'Negra + guardafangos todoterreno + placa protectora caja transferencia',
    'RAMBOX®':            '—',
    'Batea':              'Protección aspersión + puerta eléctrica con apertura remota + escalón desplegable + iluminación LED + 4 ganchos',
    'Colores disponibles':'Hydro Blue, Flame Red, Billet Silver, Bright White, Diamond Black Crystal',
  },
  tecnologia: {
    'Audio':        'Harman Kardon® Premium — 19 bocinas',
    'Manos libres': '—',
  },
})

const RAM_1500_TRADESMAN_V6_4X4: Categoria[] = merge(RAM_1500_TRADESMAN_V6_4X2, {
  desempeno: {
    'Tracción':            '4x4',
    'Caja de transferencia':'Electrónica',
    'Consumo ciudad':      '9.05 km/L',
    'Consumo carretera':   '12.9 km/L',
    'Consumo combinado':   '10.5 km/L',
  },
  dimensiones: {
    'Capacidad de carga': '830 kg',
  },
})

const RAM_1500_BIGHORN: Categoria[] = merge(RAM_1500_TUNGSTEN, {
  desempeno: {
    'Motor':               '3.6L V6 24V VVT eTorque Engine',
    'Potencia':            '305 HP @ 6,400 rpm',
    'Torque':              '269 lb-ft @ 4,800 rpm',
    'Suspensión delantera':'Horquillas independientes con resortes helicoidales, amortiguadores Twin-Tube y barra estabilizadora',
    'Suspensión trasera':  '5 links con resortes helicoidales, amortiguadores Twin-Tube, eje sólido y barra estabilizadora',
    'Sistema motor':       'eTorque mild-hybrid 48V',
  },
  dimensiones: {
    'Capacidad de carga':    '830 kg',
    'Capacidad de arrastre': '3,370 kg',
    'Neumáticos':            'Bridgestone All Terrain 275/55R20',
    'Rines':                 'Aluminio 20×9.0 negro',
  },
  remolque: {
    'Arnés':                     '7 pines',
    'Gancho del remolque':       '—',
    'Control dirección inversa': '—',
    'Monitor presión remolque':  '—',
  },
  interior: {
    'Tapicería':             'Tela premium',
    'Asiento conductor':     'Eléctrico 8 posiciones + lumbar 2 dirs',
    'Asiento pasajero':      'Manual 4 posiciones',
    'Asientos delanteros':   '—',
    'Asientos traseros':     'Reclinable 60/40',
    'Volante':               'Forrado en piel',
    'Pedales':               '—',
    'Memoria':               '—',
    'Espejo retrovisor':     'Con atenuación automática digital',
    'Iluminación ambiental': '—',
    'Control activo ruido':  '—',
    'Tapetes':               '—',
  },
  exterior: {
    'Faros':               'LED reflector automático luces altas y bajas',
    'Luces antiniebla':    'LED',
    'Luces traseras':      '—',
    'Animación iluminación':'—',
    'Espejos exteriores':  'Negros, eléctricos, calefactables, plegables automáticos, atenuación automática, luz direccional/cortesía, gran angular convexo',
    'Estribos':            'Laterales en color negro',
    'Altura de manejo':    'Elevada',
    'Techo':               '—',
    'Performance Hood':    '—',
    'Escape':              '—',
    'Manijas exteriores':  'Negro',
    'Fascia delantera':    'Al color + placa protectora caja transferencia',
    'Limpiaparabrisas':    '—',
    'RAMBOX®':             '—',
    'Batea':               'Protección aspersión + escalón desplegable + iluminación LED + 4 ganchos',
    'Colores disponibles': 'Billet Silver, Bright White, Diamond Black, Granite Metallic, Delmonico Red',
  },
  tecnologia: {
    'Pantalla principal':  'Táctil 12" — Apple CarPlay® y Android Auto',
    'Clúster':             'TFT color 7"',
    'Pantalla pasajero':   '—',
    'Head-Up Display':     '—',
    'Audio':               '9 bocinas + subwoofer',
    'Manos libres':        '—',
    'Carga inalámbrica':   '1 celular',
  },
  seguridad: {
    'Control antivuelco':          '—',
    'Cámara':                      'Trasera',
    'Colisión intersecciones':     '—',
    'Dirección evasiva':           '—',
    'Señales de tráfico':          '—',
    'Conductor somnoliento':       '—',
    'Sistema activo conducción':   '—',
    'Control velocidad selectiva': 'Sí',
  },
})

const RAM_1500_LARAMIE: Categoria[] = merge(RAM_1500_BIGHORN, {
  desempeno: {
    'Motor':               '3.0L I6 Hurricane SO Twin Turbo ESS',
    'Potencia':            '420 HP @ 5,200 rpm',
    'Torque':              '469 lb-ft @ 3,500 rpm',
    'Sistema motor':       'Stop-Start con batería auxiliar',
    'Alternador':          '230A',
    'Batería':             '700 amp, libre de mantenimiento',
    'Inversor':            '400W',
    'Tanque de combustible':'98 L',
  },
  dimensiones: {
    'Capacidad de carga':    '760 kg',
    'Capacidad de arrastre': '5,080 kg',
    'Neumáticos':            'Pirelli All Season 285/45R22XL',
    'Rines':                 'Aluminio forjado 22×9.0 negro',
  },
  remolque: {
    'Arnés': '7 pines + conector 12 vías/1 vía',
  },
  interior: {
    'Tapicería':             'Piel envolvente',
    'Asiento pasajero':      'Eléctrico 8 posiciones + lumbar 2 dirs',
    'Asientos delanteros':   'Calefacción y ventilación',
    'Asientos traseros':     'Calefacción + reclinables',
    'Volante':               'Calefactable en piel',
    'Pedales':               'Ajuste eléctrico',
    'Memoria':               'Asiento conductor, espejos y pedales',
    'Espejo retrovisor':     'Digital con modo remolque',
    'Iluminación ambiental': 'LED',
  },
  exterior: {
    'Animación iluminación': 'Frontal y trasera exterior',
    'Escape':                'Doble con puntas brillantes',
    'Espejos exteriores':    'Negros, eléctricos premium, calefactables, plegables eléctricos automáticos, atenuación automática, luz direccional/cortesía, gran angular convexo, luz aproximación',
    'Estribos':              'Plegables eléctricos',
    'Limpiaparabrisas':      'Sensibles a la lluvia',
    'Manijas exteriores':    'Al color de la carrocería',
    'RAMBOX®':               'Opcional',
    'Techo':                 'Corredizo panorámico doble panel',
  },
  tecnologia: {
    'Pantalla principal':  'Táctil 14.4" — Apple CarPlay® y Android Auto',
    'Clúster':             'TFT color 12"',
    'Pantalla pasajero':   '10.25"',
    'Head-Up Display':     'Sí',
    'Audio':               'Harman Kardon® Premium — 19 bocinas',
    'Carga inalámbrica':   '2 celulares simultáneos',
  },
  seguridad: {
    'Conductor somnoliento':     'Detección activa',
    'Dirección evasiva':         'Sí',
    'Señales de tráfico':        'Reconocimiento automático',
    'Sistema activo conducción': 'Sí',
    'Colisión intersecciones':   'Asistencia activa',
    'Cámara':                    'Visión envolvente 360°',
  },
})

const RAM_1500_LIMITED: Categoria[] = merge(RAM_1500_LARAMIE, {
  desempeno: {
    'Motor':               '3.0L I6 Hurricane HO Twin Turbo ESS',
    'Potencia':            '540 HP @ 6,200 rpm',
    'Torque':              '521 lb-ft @ 3,500 rpm',
    'Suspensión delantera':'Independiente brazos cortos/largos, Quadra-Lift® neumática semiactiva, barra estabilizadora',
    'Suspensión trasera':  'Independiente 5 enlaces, resortes helicoidales, Quadra-Lift® neumática semiactiva, enlaces aluminio fundido',
    'Sistema motor':       '—',
    'Alternador':          '—',
    'Batería':             '—',
    'Inversor':            '—',
    'Tanque de combustible':'—',
  },
  dimensiones: {
    'Capacidad de carga':    '610 kg',
    'Capacidad de arrastre': '4,380 kg',
    'Rines':                 '22×9.0 pulido con insertos',
  },
  interior: {
    'Tapicería':         'Piel premium envolvente',
    'Asiento conductor': 'Eléctrico 8 posiciones + lumbar 4 dirs + masaje + memoria',
    'Asiento pasajero':  'Eléctrico 8 posiciones + lumbar 4 dirs + masaje',
    'Asientos traseros': 'Calefacción, ventilación y reclinables',
    'Volante':           'Calefactable en piel con insertos de madera',
  },
  exterior: {
    'Faros':              'LED bifunción automáticos',
    'Luces traseras':     'LED',
    'Espejos exteriores': 'Cromados, eléctricos premium, calefactados, plegables eléctricos automáticos, atenuación automática, luz direccional/cortesía, gran angular convexo, luz aproximación',
    'Fascia delantera':   'Cromada (delantera y trasera)',
    'RAMBOX®':            'Sistema gestión de carga',
    'Batea':              'Protección aspersión + puerta multifunción opcional + escalón desplegable + iluminación LED + 4 ganchos',
  },
})

// RAM 700 2026
// ─────────────────────────────────────────────────────────────────────────────

const RAM_700_TRADESMAN_REG_CAB: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                valor: '1.3L Firefly 4 cilindros' },
      { label: 'Potencia',             valor: '98 HP @ 6,000 rpm' },
      { label: 'Torque',               valor: '94 lb-ft @ 4,000 rpm' },
      { label: 'Transmisión',          valor: 'Manual 5 velocidades con indicador electrónico' },
      { label: 'Tracción',             valor: '4x2 FWD (Delantera)' },
      { label: 'Dirección',            valor: 'Electroasistida' },
      { label: 'Diámetro de giro',     valor: '10.7 m' },
      { label: 'Frenos delanteros',    valor: 'Disco' },
      { label: 'Frenos traseros',      valor: 'Tambor' },
      { label: 'Suspensión delantera', valor: 'McPherson' },
      { label: 'Suspensión trasera',   valor: 'Eje rígido de muelles longitudinales' },
      { label: 'Consumo ciudad',       valor: '16.2 km/L' },
      { label: 'Consumo carretera',    valor: '21.8 km/L' },
      { label: 'Consumo combinado',    valor: '18.3 km/L' },
    ],
  },
  {
    id: 'dimensiones', nombre: 'Dimensiones y Capacidades', specs: [
      { label: 'Largo',                   valor: '4,474 mm' },
      { label: 'Ancho',                   valor: '1,732 mm' },
      { label: 'Alto',                    valor: '1,595 mm' },
      { label: 'Distancia entre ejes',    valor: '2,737 mm' },
      { label: 'Pasajeros',               valor: '2' },
      { label: 'Volumen de carga',        valor: '1,354 L' },
      { label: 'Capacidad de carga',      valor: '750 kg' },
      { label: 'Capacidad de arrastre',   valor: '400 kg' },
      { label: 'Ancho carga máximo',      valor: '1,336 mm' },
      { label: 'Altura de carga',         valor: '606 mm' },
      { label: 'Longitud carga máxima',   valor: '1,717 mm' },
      { label: 'Neumáticos',              valor: '185/60R15' },
      { label: 'Rines',                   valor: 'Acero 15"' },
      { label: 'Llanta de repuesto',      valor: 'Tamaño completo (debajo área de carga)' },
      { label: 'Placa protectora cárter', valor: '—' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Faros',                 valor: 'Halógeno' },
      { label: 'DRL',                   valor: 'Halógeno' },
      { label: 'Luces antiniebla',      valor: '—' },
      { label: 'Micas delanteras',      valor: 'Parcialmente ahumadas' },
      { label: 'Parrilla',              valor: 'Color negro R-A-M' },
      { label: 'Fascia',                valor: 'Negra con texturizado' },
      { label: 'Manijas',               valor: 'Negras con texturizado' },
      { label: 'Espejos',               valor: 'Laterales negros manuales' },
      { label: 'Puertas',               valor: '2' },
      { label: 'Sensor temperatura',    valor: '—' },
      { label: 'Compuerta combustible', valor: 'Manual' },
      { label: 'Ganchos carga',         valor: '10' },
      { label: 'Batea',                 valor: 'Recubrimiento Bedliner + cubierta lona + iluminación' },
      { label: 'Barras techo',          valor: '—' },
      { label: 'Roll Bar',              valor: '—' },
      { label: 'Colores disponibles',   valor: 'Blanco, Plata, Rojo Colorado' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Tapicería',              valor: 'Tela Heavy Duty gris obscuro' },
      { label: 'A/C',                    valor: 'Manual' },
      { label: 'Asiento conductor',      valor: 'Manual 4 posiciones' },
      { label: 'Pasajeros 2ª fila',      valor: '—' },
      { label: 'Volante',                valor: 'Con ajuste de altura' },
      { label: 'Clúster',                valor: 'TFT 3.5"' },
      { label: 'Pantalla',               valor: '7" — Apple CarPlay® y Android Auto inalámbrico' },
      { label: 'Audio',                  valor: '2 bocinas + 2 tweeters' },
      { label: 'Conectividad',           valor: 'USB + toma 12V' },
      { label: 'Cargador inalámbrico',   valor: '—' },
      { label: 'Modo sport',             valor: '—' },
      { label: 'Paletas de cambios',     valor: '—' },
      { label: 'Cristales traseros',     valor: '—' },
      { label: 'Ventana trasera',        valor: 'Fija' },
      { label: 'Desempañador trasero',   valor: '—' },
      { label: 'Guantera iluminada',     valor: '—' },
      { label: 'Memoria espejo reversa', valor: '—' },
      { label: 'Descansabrazos',         valor: '—' },
      { label: 'Tapetes',                valor: '—' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Frenos ABS',            valor: 'Sí' },
      { label: 'ESC',                   valor: 'Sí' },
      { label: 'EBD',                   valor: 'Sí' },
      { label: 'Control tracción (TC+)', valor: 'Sí' },
      { label: 'Arranque en pendiente', valor: 'Sí' },
      { label: 'Bolsas de aire',        valor: 'Delanteras + laterales delanteras' },
      { label: 'Cámara',                valor: 'Reversa con guías activas' },
      { label: 'Sensores reversa',      valor: 'Acústicos' },
      { label: 'TPMS',                  valor: '—' },
      { label: 'ISOFIX',                valor: '—' },
      { label: 'Cinturones delanteros', valor: 'Con pretensores' },
      { label: 'Cinturones traseros',   valor: '—' },
      { label: 'Alarma antirrobo',      valor: 'Sí' },
      { label: 'Llave de codificación', valor: 'Navaja con control remoto' },
      { label: 'FPS',                   valor: 'Sí' },
    ],
  },
]

const RAM_700_TRADESMAN_CREW_CAB: Categoria[] = merge(RAM_700_TRADESMAN_REG_CAB, {
  desempeno: {
    'Consumo ciudad':    '16.7 km/L',
    'Consumo carretera': '21.0 km/L',
    'Consumo combinado': '18.4 km/L',
  },
  dimensiones: {
    'Alto':                   '1,586 mm',
    'Pasajeros':              'Hasta 5',
    'Volumen de carga':       '844 L',
    'Capacidad de carga':     '650 kg',
    'Ancho carga máximo':     '1,310 mm',
    'Longitud carga máxima':  '1,178 mm',
    'Placa protectora cárter':'Sí',
  },
  exterior: {
    'Puertas':       '4',
    'Ganchos carga': '8',
  },
  interior: {
    'Pasajeros 2ª fila':   '3 pasajeros con cabeceras',
    'Audio':               '6 bocinas + 2 tweeters',
    'Cristales traseros':  'Eléctricos',
    'Desempañador trasero':'Sí',
  },
  seguridad: {
    'ISOFIX':             'Sí',
    'Cinturones traseros':'3 de 3 puntos',
  },
})

const RAM_700_BIGHORN_MT: Categoria[] = merge(RAM_700_TRADESMAN_CREW_CAB, {
  dimensiones: {
    'Alto':  '1,585 mm',
    'Rines': 'Acero 15" / aluminio 15" (opcional)',
  },
  exterior: {
    'Luces antiniebla':    'Sí',
    'Espejos':             'Eléctricos al color con direccionales',
    'Fascia':              'Al color de la carrocería',
    'Manijas':             'Al color de la carrocería',
    'Sensor temperatura':  'Sí',
    'Compuerta combustible':'Eléctrica',
    'Colores disponibles': 'Blanco, Plata, Gris Cuarzo, Rojo Colorado',
  },
  interior: {
    'Guantera iluminada':     'Sí',
    'Memoria espejo reversa': 'Automática (espejo derecho en reversa)',
  },
  seguridad: {
    'TPMS': 'Sí',
  },
})

const RAM_700_BIGHORN_CVT: Categoria[] = merge(RAM_700_BIGHORN_MT, {
  desempeno: {
    'Transmisión':      'CVT',
    'Consumo ciudad':   '16.2 km/L',
    'Consumo carretera':'22.0 km/L',
    'Consumo combinado':'18.4 km/L',
  },
  dimensiones: {
    'Capacidad de carga': '600 kg',
  },
  interior: {
    'Volante':            'Forrado en piel',
    'Cargador inalámbrico':'Sí',
    'Modo sport':         'Sí',
    'Paletas de cambios': 'Sí',
  },
})

const RAM_700_LARAMIE: Categoria[] = merge(RAM_700_BIGHORN_CVT, {
  desempeno: {
    'Motor':              '1.0L Turbo 3 cilindros',
    'Potencia':           '118 HP @ 5,750 rpm',
    'Torque':             '148 lb-ft @ 1,750 rpm',
    'Diámetro de giro':   '10.8 m',
    'Consumo ciudad':     '15.2 km/L',
    'Consumo carretera':  '19.9 km/L',
    'Consumo combinado':  '17.0 km/L',
  },
  dimensiones: {
    'Largo':              '4,480 mm',
    'Capacidad de carga': '650 kg',
    'Neumáticos':         '205/55R16 ALL TERRAIN',
    'Rines':              'Aluminio 16"',
  },
  exterior: {
    'Faros':           'LED',
    'DRL':             'LED',
    'Luces antiniebla':'LED',
    'Parrilla':        'Nueva fascia y parrilla R-A-M',
    'Fascia':          'Al color + bisel plateado inferior',
    'Barras techo':    'Longitudinales',
    'Roll Bar':        'Sí',
  },
  interior: {
    'Tapicería':      'Piel',
    'A/C':            'Automático',
    'Descansabrazos': 'Conductor',
    'Tapetes':        'Con bordado LARAMIE',
  },
})

// ─────────────────────────────────────────────────────────────────────────────
// RAM 1200 2026  —  Tradesman (Chassis / Regular / Crew) / Bighorn / Laramie
// ─────────────────────────────────────────────────────────────────────────────

const RAM_1200_TRADESMAN_CHASSIS: Categoria[] = [
  {
    id: 'desempeno', nombre: 'Desempeño', specs: [
      { label: 'Motor',                 valor: '2.0L Turbo I4' },
      { label: 'Potencia',              valor: '217 HP @ 5,500 rpm' },
      { label: 'Torque',                valor: '288 lb-pie @ 1,900–3,300 rpm' },
      { label: 'Transmisión',           valor: 'Manual 6 velocidades' },
      { label: 'Tracción',              valor: '4X2 (2WD)' },
      { label: 'Selector de tracción',  valor: 'No incluido' },
      { label: 'Bloqueo diferencial trasero', valor: 'No incluido' },
      { label: 'Modos de manejo',       valor: 'No incluido' },
      { label: 'Dirección',             valor: 'Eléctrica' },
      { label: 'Diámetro de giro',      valor: '12.98 m' },
      { label: 'Suspensión delantera',  valor: 'Independiente, doble brazo de control' },
      { label: 'Suspensión trasera',    valor: 'Eje rígido con 5 ballestas longitudinales' },
      { label: 'Frenos',                valor: 'Discos delanteros ventilados / tambor trasero' },
      { label: 'Tanque de combustible', valor: '70 L (gasolina)' },
      { label: 'Rendimiento combinado', valor: '8.10 km/l' },
    ],
  },
  {
    id: 'dimensiones', nombre: 'Dimensiones y Capacidades', specs: [
      { label: 'Largo',                 valor: '5,330 mm' },
      { label: 'Ancho',                 valor: '1,963 mm' },
      { label: 'Alto',                  valor: '1,858 mm' },
      { label: 'Distancia entre ejes',  valor: '3,180 mm' },
      { label: 'Capacidad de carga',    valor: '1,315 kg' },
      { label: 'Capacidad de arrastre', valor: '3,000 kg' },
      { label: 'Volumen de carga',      valor: '—' },
      { label: 'Longitud de carga máxima', valor: '—' },
      { label: 'Capacidad de pasajeros', valor: '3' },
      { label: 'Rines',                 valor: 'Acero 16"' },
      { label: 'Neumáticos',           valor: '245/70 R16' },
      { label: 'Llanta de refacción',   valor: 'Tamaño completo con rin de acero' },
    ],
  },
  {
    id: 'exterior', nombre: 'Exterior', specs: [
      { label: 'Faros',                 valor: 'Halógeno' },
      { label: 'Luces diurnas (DRL)',   valor: 'Sí' },
      { label: 'Faros de niebla',       valor: 'No incluido' },
      { label: 'Espejos laterales',     valor: 'Eléctricos con direccional, color negro' },
      { label: 'Manijas exteriores',    valor: 'Color negro' },
      { label: 'Parrilla',              valor: 'Color negro' },
      { label: 'Fascias',               valor: 'Delantera y trasera en negro' },
      { label: 'Estribos laterales',    valor: 'No incluido' },
      { label: 'Placa protectora de motor', valor: 'Sí' },
      { label: 'Loderas',               valor: 'Delanteras' },
    ],
  },
  {
    id: 'interior', nombre: 'Interior', specs: [
      { label: 'Aire acondicionado',    valor: 'Manual' },
      { label: 'Asientos',              valor: 'Tela, banca corrida sin consola central' },
      { label: 'Asiento conductor',     valor: 'Ajuste manual' },
      { label: 'Asientos traseros 60/40', valor: 'No incluido' },
      { label: 'Clúster',               valor: '3.5" monocromático' },
      { label: 'Pantalla / Audio',      valor: 'Radio AM/FM, conexión inalámbrica, MP3' },
      { label: 'Altavoces',             valor: '2' },
      { label: 'Puertos USB',           valor: '2 delanteros' },
      { label: 'Cristales eléctricos',  valor: 'Bajada de un toque (conductor)' },
      { label: 'Volante',               valor: 'Ajuste de altura, controles de audio' },
      { label: 'Volante en piel',       valor: 'No incluido' },
      { label: 'Computadora de viaje',  valor: 'Sí' },
      { label: 'Guantera con iluminación LED', valor: 'Sí' },
    ],
  },
  {
    id: 'seguridad', nombre: 'Seguridad', specs: [
      { label: 'Bolsas de aire frontales', valor: 'Conductor y pasajero' },
      { label: 'Bolsas laterales delanteras', valor: 'No incluido' },
      { label: 'Bolsas tipo cortina',   valor: 'No incluido' },
      { label: 'Frenos ABS',            valor: 'Sí' },
      { label: 'Control de estabilidad (ESP)', valor: 'Sí' },
      { label: 'Control de tracción',   valor: 'Sí' },
      { label: 'Control descenso pendientes (HDC)', valor: 'No incluido' },
      { label: 'Asistencia arranque en pendiente (HSA)', valor: 'Sí' },
      { label: 'Monitoreo presión neumáticos (TPM)', valor: 'Sí' },
      { label: 'Cámara de estacionamiento', valor: 'No incluido' },
      { label: 'Sensores de estacionamiento', valor: 'No incluido' },
      { label: 'Visión 360°',           valor: 'No incluido' },
      { label: 'Keyless Entry & Go',    valor: 'No incluido' },
      { label: 'Anclaje ISOFIX',        valor: 'No incluido' },
      { label: 'Inmovilizador de motor', valor: 'Sí' },
      { label: 'Alarma antirrobo perimetral', valor: 'Sí' },
    ],
  },
]

const RAM_1200_TRADESMAN_REG_CAB: Categoria[] = merge(RAM_1200_TRADESMAN_CHASSIS, {
  desempeno: {
    'Rendimiento combinado': '9.9 km/l',
  },
  dimensiones: {
    'Capacidad de carga':       '1,210 kg',
    'Volumen de carga':         '1,914 L',
    'Longitud de carga máxima': '2,400 mm',
  },
  exterior: {
    'Loderas': 'Delanteras y traseras',
  },
})

const RAM_1200_TRADESMAN_CREW_CAB: Categoria[] = merge(RAM_1200_TRADESMAN_CHASSIS, {
  desempeno: {
    'Frenos':                'Discos delanteros ventilados y disco trasero',
    'Rendimiento combinado': '10.2 km/l',
  },
  dimensiones: {
    'Capacidad de carga':       '1,115 kg',
    'Volumen de carga':         '1,276 L',
    'Longitud de carga máxima': '1,600 mm',
    'Capacidad de pasajeros':   '5',
    'Rines':                    'Acero 17"',
    'Neumáticos':               '265/65 R17',
  },
  exterior: {
    'Loderas': 'Delanteras y traseras',
  },
  interior: {
    'Asientos':             'Tela tacto piel',
    'Asientos traseros 60/40': 'Sí',
    'Altavoces':            '4',
  },
  seguridad: {
    'Bolsas laterales delanteras': 'Sí',
    'Bolsas tipo cortina':         'Sí',
    'Anclaje ISOFIX':              'Sí',
  },
})

const RAM_1200_BIGHORN: Categoria[] = merge(RAM_1200_TRADESMAN_CREW_CAB, {
  desempeno: {
    'Transmisión':           'Automática 8 velocidades',
    'Modos de manejo':       'Normal / Sport',
    'Rendimiento combinado': '10.1 km/l',
  },
  dimensiones: {
    'Alto':                  '1,897 mm',
    'Capacidad de carga':    '1,090 kg',
    'Capacidad de arrastre': '2,500 kg',
    'Rines':                 'Aluminio 17", cara pulida y pockets negros',
    'Neumáticos':            '265/65 R17',
  },
  exterior: {
    'Faros de niebla':     'LED con función cornering',
    'Espejos laterales':   'Calefactables y abatibles, color carrocería',
    'Manijas exteriores':  'Color carrocería',
    'Parrilla':            'Con detalles en cromo',
    'Fascias':             'Delantera al color, trasera metálica',
    'Estribos laterales':  'Sí',
  },
  interior: {
    'Pantalla / Audio':  'Táctil 10", Apple CarPlay y Android Auto, disco duro 10 GB',
    'Puertos USB':       '2 delanteros y 1 trasero',
    'Volante en piel':   'Sí',
  },
  seguridad: {
    'Cámara de estacionamiento':   'Sí',
    'Sensores de estacionamiento': 'Traseros',
    'Keyless Entry & Go':          'Sí',
  },
})

const RAM_1200_BIGHORN_4X4: Categoria[] = merge(RAM_1200_BIGHORN, {
  desempeno: {
    'Tracción':                    '4X4 (4WD)',
    'Selector de tracción':        'Sí (2H / 4Auto / 4L)',
    'Bloqueo diferencial trasero': 'Sí',
    'Modos de manejo':             'Normal / Sport / Snow / Sand',
  },
  seguridad: {
    'Control descenso pendientes (HDC)': 'Sí',
  },
})

const RAM_1200_LARAMIE: Categoria[] = merge(RAM_1200_BIGHORN_4X4, {
  desempeno: {
    'Rendimiento combinado': '9.7 km/l',
  },
  dimensiones: {
    'Capacidad de carga': '1,075 kg',
    'Rines':              'Aluminio 18", cara pulida y pockets negros',
    'Neumáticos':         '265/60 R18',
  },
  exterior: {
    'Faros':              'Halógeno + LED automático',
    'Luces diurnas (DRL)': 'LED',
    'Espejos laterales':  'Cromados, calefactables y abatibles',
    'Manijas exteriores': 'Cromadas',
  },
  interior: {
    'Aire acondicionado': 'Automático de doble zona',
    'Asientos':           'Piel con ajuste eléctrico',
    'Clúster':            '4.2" TFT a color',
    'Altavoces':          '4 + 2 tweeters',
    'Asiento conductor':  'Ajuste eléctrico',
  },
  seguridad: {
    'Visión 360°':                  'Sí',
    'Sensores de estacionamiento':  'Delanteros y traseros',
  },
})

export const MODELOS_RAM: ModeloFicha[] = [
  {
    id: 'ram-4000-2026',
    marca: 'RAM',
    modelo: 'RAM 4000',
    año: 2026,
    versiones: [
      { id: 'reg-cab-p',  nombre: 'Reg Cab Chassis P',  categorias: RAM_4000_REG_CAB_P  },
      { id: 'reg-cab-pl', nombre: 'Reg Cab Chassis PL', categorias: RAM_4000_REG_CAB_PL },
      { id: 'crew-cab',   nombre: 'Crew Cab Chassis',   categorias: RAM_4000_CREW_CAB   },
    ],
  },
  {
    id: 'ram-1500-2026',
    marca: 'RAM',
    modelo: 'RAM 1500',
    año: 2026,
    versiones: [
      { id: 'tungsten',          nombre: 'Tungsten',             categorias: RAM_1500_TUNGSTEN           },
      { id: 'bighorn-off-road',  nombre: 'Bighorn Off Road',     categorias: RAM_1500_BIGHORN            },
      { id: 'laramie-night',     nombre: 'Laramie Night Edition', categorias: RAM_1500_LARAMIE           },
      { id: 'limited',           nombre: 'Limited',              categorias: RAM_1500_LIMITED            },
      { id: 'rho',               nombre: 'RHO',                  categorias: RAM_1500_RHO               },
      { id: 'tradesman-v6-4x2',  nombre: 'Tradesman V6 4x2',    categorias: RAM_1500_TRADESMAN_V6_4X2  },
      { id: 'tradesman-v6-4x4',  nombre: 'Tradesman V6 4x4',    categorias: RAM_1500_TRADESMAN_V6_4X4  },
      { id: 'tradesman-i6-4x4',  nombre: 'Tradesman I6 4x4',    categorias: RAM_1500_TRADESMAN         },
    ],
  },
  {
    id: 'ram-1200-2026',
    marca: 'RAM',
    modelo: 'RAM 1200',
    año: 2026,
    versiones: [
      { id: 'tradesman-chassis-cab', nombre: 'Tradesman Chassis Cab', categorias: RAM_1200_TRADESMAN_CHASSIS },
      { id: 'tradesman-regular-cab', nombre: 'Tradesman Regular Cab', categorias: RAM_1200_TRADESMAN_REG_CAB  },
      { id: 'tradesman-crew-cab',    nombre: 'Tradesman Crew Cab',    categorias: RAM_1200_TRADESMAN_CREW_CAB },
      { id: 'bighorn-crew-cab',      nombre: 'Bighorn Crew Cab',      categorias: RAM_1200_BIGHORN            },
      { id: 'bighorn-crew-cab-4x4',  nombre: 'Bighorn Crew Cab 4X4',  categorias: RAM_1200_BIGHORN_4X4        },
      { id: 'laramie-crew-cab-4x4',  nombre: 'Laramie Crew Cab 4X4',  categorias: RAM_1200_LARAMIE            },
    ],
  },
  {
    id: 'ram-700-2026',
    marca: 'RAM',
    modelo: 'RAM 700',
    año: 2026,
    versiones: [
      { id: 'tradesman-reg-cab',  nombre: 'Tradesman Regular Cab', categorias: RAM_700_TRADESMAN_REG_CAB  },
      { id: 'tradesman-crew-cab', nombre: 'Tradesman Crew Cab',    categorias: RAM_700_TRADESMAN_CREW_CAB },
      { id: 'bighorn-mt',         nombre: 'Bighorn MT',            categorias: RAM_700_BIGHORN_MT         },
      { id: 'bighorn-cvt',        nombre: 'Bighorn CVT',           categorias: RAM_700_BIGHORN_CVT        },
      { id: 'laramie-cvt-turbo',  nombre: 'Laramie CVT Turbo',     categorias: RAM_700_LARAMIE            },
    ],
  },
]
